### ISSUE TITLE
Tips for getting to work on Windows 10 latest Docker version

### ISSUE THREAD

**Issue by tharris9d** [tgorgdotcom/locast2plex#1]
Do you have any tips on getting this to work on Windows 10? If it's not possible let me know. No rush it would be cool to get it working....

**Comment by sheilnaik** [comment]
It works for me just fine. What’s the issue you’re having? Are you unable to install Docker on Windows 10 Home?

**Comment by tharris9d** [comment]
Thanks sheilnaik! I am getting Python version errors. Do you know what exact version of Python is used for the project?

**Comment by tgorgdotcom** [comment]
The version that is reported on the docker image is Python 2.7.15.  Do you have a specific error message you're running into?

**Comment by tharris9d** [comment]
![locast2PlexError](https://user-images.githubusercontent.com/217445/79487339-f7764280-7fcc-11ea-9903-9787eae0b578.PNG)
I am getting the error in the image.

**Comment by tharris9d** [comment]
Here is the log from Docker docker-compose up using the GitHub source. I can attach as tuner but no channels.
![NoChannels](https://user-images.githubusercontent.com/217445/79596100-d1b47080-8094-11ea-8411-9b60efaa4957.PNG)

**Comment by tharris9d** [comment]
Attaching to locast2plex-master_locast2plex_1

locast2plex_1 | Locast2Plex v0.2.2

locast2plex_1 | Logging into Locast using username tom.harris@9di.com...

locast2plex_1 | Validating User Info...

locast2plex_1 | User Info obtained.

locast2plex_1 | User didDonate: True

locast2plex_1 | User donationExpire: 1589248849

locast2plex_1 | Opening/Creating locastChannels.m3u8...

locast2plex_1 | Getting user location...

locast2plex_1 | Getting user's media market (DMA)...

locast2plex_1 | Getting list of stations based on DMA...

locast2plex_1 | Traceback (most recent call last):

locast2plex_1 | File "/app/main.py", line 303, in <module>

locast2plex_1 | Getting station info for KCBSDT...

locast2plex_1 | Determining best video stream for KCBSDT...

locast2plex_1 | KCBSDT will use 1280x720 resolution at 2700000bps

locast2plex_1 | Getting station info for KNBCDT...

locast2plex_1 | Determining best video stream for KNBCDT...

locast2plex_1 | KNBCDT will use 1280x720 resolution at 2700000bps

locast2plex_1 | Getting station info for KNBCDT2...

locast2plex_1 | Determining best video stream for KNBCDT2...

locast2plex_1 | if (not locast_login()) or (not validate_user()) or (not generate_m3u()):

locast2plex_1 | File "/app/main.py", line 271, in generate_m3u

locast2plex_1 | " resolution at " + str(bestStream.stream_info.bandwidth) + "bps")

locast2plex_1 | AttributeError: 'NoneType' object has no attribute 'stream_info'

locast2plex_1 | File "/app/main.py", line 71, in locast_login

locast2plex_1 | print("Error during login: " + urlError.reason.strerror)

locast2plex_1 | AttributeError: 'str' object has no attribute 'strerror'

locast2plex_1 | Running Telly. Configured to run on IP 127.0.0.1...

locast2plex_1 | time="2020-04-17T17:06:35Z" level=info msg="telly is preparing to go live (version=1.1.0.6, branch=dev, revision=741108cd2100cf9f4d3a13f771d1ebe5132baae6)"

locast2plex_1 | time="2020-04-17T17:06:35Z" level=info msg="Loading M3U from locastChannels.m3u8"

locast2plex_1 | time="2020-04-17T17:06:35Z" level=info msg="Loaded 0 channels into the lineup from "

locast2plex_1 | time="2020-04-17T17:06:35Z" level=info msg="telly is live and on the air!"

locast2plex_1 | time="2020-04-17T17:06:35Z" level=info msg="Broadcasting from http://0.0.0.0:6077/"

locast2plex_1 | time="2020-04-17T17:06:35Z" level=info msg="EPG URL: http://0.0.0.0:6077/epg.xml"

locast2plex_1 | time="2020-04-17T17:09:49Z" level=info msg="Loading M3U from locastChannels.m3u8"

locast2plex_1 | time="2020-04-17T17:09:49Z" level=info msg="Loaded 0 channels into the lineup from "

locast2plex-master_locast2plex_1 exited with code 137

**Comment by tgorgdotcom** [comment]
Hmmm.  Looks like one of the stations are reporting 0 streams.  And also my error handling is not working so well.  I just pushed an update to fix both (essentially I'll skip channels with 0 streams now instead of crashing and burning).  If you could give it a shot and report back, that would be excellent.

**Comment by tharris9d** [comment]
When using docker-compose up on latest code it gets stuck on line 271.
Determining best video stream for KCBSDT...
locast2plex_1  | KCBSDT will use 1280x720 resolution at 2700000bps
locast2plex_1  | Getting station info for KNBCDT...
locast2plex_1  | Determining best video stream for KNBCDT...
locast2plex_1  | KNBCDT will use 1280x720 resolution at 2700000bps
locast2plex_1  | Getting station info for KNBCDT2...
locast2plex_1  | Determining best video stream for KNBCDT2...
locast2plex_1  |     if (not locast_login()) or (not validate_user()) or (not generate_m3u()):
locast2plex_1  |   File "/app/main.py", line 271, in generate_m3u
locast2plex_1  |     " resolution at " + str(bestStream.stream_info.bandwidth) + "bps")
locast2plex_1  | AttributeError: 'NoneType' object has no attribute 'stream_info'

**Comment by tharris9d** [comment]
When running docker run -e username=tom.harris@9di.com -e password=3343Buzz9d3! -e listen_addy=127.0.0.1 -p 6077:6077 tgorg/locast2plex        
We get this error

Locast2Plex v0.2.2
Logging into Locast using username tom.harris@9di.com...
Traceback (most recent call last):
  File "/app/main.py", line 303, in <module>
    if (not locast_login()) or (not validate_user()) or (not generate_m3u()):
  File "/app/main.py", line 71, in locast_login
    print("Error during login: " + urlError.reason.strerror)
AttributeError: 'str' object has no attribute 'strerror'
PS C:\Users\tharr\Downloads\locast2plex-master_update\locast2plex-master>

**Comment by tharris9d** [comment]
It looks like it's not finding ANY channels.
So weird.

locast2plex_1 | Running Telly. Configured to run on IP 127.0.0.1...

locast2plex_1 | time="2020-04-19T01:55:40Z" level=info msg="telly is preparing to go live (version=1.1.0.6, branch=dev, revision=741108cd2100cf9f4d3a13f771d1ebe5132baae6)"

locast2plex_1 | time="2020-04-19T01:55:40Z" level=info msg="Loading M3U from locastChannels.m3u8"

locast2plex_1 | time="2020-04-19T01:55:40Z" level=info msg="Loaded 0 channels into the lineup from "

locast2plex_1 | time="2020-04-19T01:55:40Z" level=info msg="telly is live and on the air!"

locast2plex_1 | time="2020-04-19T01:55:40Z" level=info msg="Broadcasting from http://0.0.0.0:6077/"

locast2plex_1 | time="2020-04-19T01:55:40Z" level=info msg="EPG URL: http://0.0.0.0:6077/epg.xml"

locast2plex_1 | time="2020-04-19T01:56:52Z" level=info msg="Loading M3U from locastChannels.m3u8"

locast2plex_1 | time="2020-04-19T01:56:52Z" level=info msg="Loaded 0 channels into the lineup from "

**Comment by tgorgdotcom** [comment]
Hmmm.  One of the error messages posted listed Locast2Plex as v0.2.2.  The latest version with the fix is v0.2.3.  You'll have to delete the current container and re-add it.  Hope that helps.

**Comment by tharris9d** [comment]
Thanks. I pulled the new version and it's working now. I have HDHomeRun 4 tuner and it seems to be conflicting. I turned off the HDHomerun Channels and am refreshing the guide to see if I can keep it working with Locast2Plex. I will keep you posted. Thanks so much for your help. I know you are busy. I appreciate it.

**Comment by tgorgdotcom** [comment]
Hello.  I just pushed an update that should resolve issues with stream limits when polling for channels.  Let me know how it goes.  Thanks!
