### ISSUE TITLE
~3 hour limit\timeout on Locast streams. 

### ISSUE THREAD

**Issue by FozzieBear** [tgorgdotcom/locast2plex#103]
Noticed this today, looks like right at ~3 hours is the limit of a continuous stream from Locast. I suspect folks aren't going to be hit super often, mainly for live\special events (sports, racing, etc), but it'd be nice to handle it gracefully when it does occur. I can start poking around at a way to try and seamlessly (to the client) restart\reconnect to Locast.

**Comment by tgorgdotcom** [comment]
I'm going to have to find a way to retry streams when they fail in ffmpeg.  This is same as #114.  Going forward I'll use that task to keep everyone posted.
