### ISSUE TITLE
I was Just Testing The Project And Got This Error

### ISSUE THREAD

**Issue by MapGuy11** [tgorgdotcom/locast2plex#11]
Sorry for the incompetents of reading what this means better. Same On Docker too.

Validating User Info...
User Info obtained.
User didDonate: False
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    if (not locast.login(CONFIG_LOCAST_USERNAME, CONFIG_LOCAST_PASSWORD)) or (not locast.validate_user()):
  File "/home/root2254/Locast2Plex/LocastService.py", line 85, in validate_user
    print("User donationExpire: " + str(userRes['donationExpire'] / 1000))
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

**Comment by tgorgdotcom** [comment]
It looks like you're using a user account that hasn't donated recently.  Additionally, it looks like I have a syntax error when looking at users who haven't donated.  

Locast usually cuts the video stream out after 15 minutes for non-donating users (or users haven't donated recently enough).  I have some checks to the beginning of the script to avoid frustration from those who may be using locast2plex with Plex's DVR feature (as that would fail 15 minutes into the recording).  If the script finds a user that hasn't donated, the code execution should end with a polite error.  But there's a bug here and it's returning a harder to understand Python error.

If you could double check if the user has donated recently (or donate if you haven't already), that would be great.  That should fix your particular issue.  I'll look into patching the syntax error on my end.

**Comment by tgorgdotcom** [comment]
Also, for clarification: donate at https://www.locast.org/

**Comment by myrison** [comment]
I had this issue as well and can confirm it went away when I donated.  $5 makes the problem go away in the interim. :)

**Comment by MapGuy11** [comment]
Yeah that account is donated. The Website works without ads or anything. I created a new account without donating to try it out. Is there anyway to try it out without donating?
