### ISSUE TITLE
New Plex server cannot play or record using original L2P instance.

### ISSUE THREAD

**Issue by CTJohnK** [tgorgdotcom/locast2plex#113]
I've installed Plex on a new Synology NAS.  I've pointed the new Plex server to the old L2P instance (still running on a RaspberryPi 4) and while I can retrieve the Guide, I cannot watch or record any show.

The old Plex server is still running (on the Pi4 as well) and playback and record functions fine.

I'm not seeing any errors in the Pi4's logs and Plex just returns either "Could not tune channel..." or "Recording failed.  Please check your tuner or antenna."

Both are on the same network.  Any idea what I'm missing?  

This is the start-up command from RC.LOCAL
sudo python /home/pi/locast2plex/main.py -u:p****@gmail.com -p:**** --debug --addy:127.0.0.1 --external_addy:192.168.100.90

**Comment by CTJohnK** [comment]
One other note - the Pi4 has mounts to the same folders on the NAS and the Pi4 is saving the recordings to the NAS.  And the "Plex" NAS user has access to those same folders.  I presume this eliminates any drive access rights.

**Comment by tgorgdotcom** [comment]
I'm thinking it has something to do with the "plex_accessible_ip" setting.  What do you have that currently set to in l2p?

**Comment by CTJohnK** [comment]
Sorry, where would I find the "plex_accessible_ip"?  I used Agent Ransack to check all the files in the L2P folder and that value is not present.

**Comment by deathbybandaid** [comment]
@CTJohnK it's a configuration item in the config file

**Comment by CTJohnK** [comment]
I don't think I was clear in my original post - I'm not running the current version of L2P, I'm still using 4.2 which does not have a config file.

In the meantime, I did try stopping the Plex instance on the Pi, rebooting the Pi and then connecting to L2P running on the Pi from the Synology.  Same issue, the guide is downloaded, but playback or recording does not work.

**Comment by CTJohnK** [comment]
Ok, I found some time to dig into this and discovered the issue.  I changed the 'addy' address from 127.0.0.1 to 192.168.100.90 and that solved the issue, now both Plex servers can see, watch and record from the one instance of l2p.  Now I just have to work on deprecating the old Plex server running on the Pi.

WAS:
sudo python /home/pi/locast2plex/main.py -u:p****@gmail.com -p:**** --debug --addy:127.0.0.1 --external_addy:192.168.100.90

Now:
sudo python /home/pi/locast2plex/main.py -u:p****@gmail.com -p:**** --debug --addy:192.168.100.90 --external_addy:192.168.100.90
