### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by DanTheTechMan** [tgorgdotcom/locast2plex#116]
Hi,

I get the following error when trying to set up Locast2Plex:

Locast2Plex v0.5.3
Tuner count set to 3
UUID set to: xxxxxxxx...
Logging into Locast using username xxxxxxxxxx@xxxxx.xxx.
Error in function login: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)
Exiting...

Is there anything that can be done about that?

I'm running this using Python 3.8.6 through the command line on a NAS running Windows Server 2008 R2,.

Any help will be greatly appreciated.

Thanks.

**Comment by deathbybandaid** [comment]
Jan 2020 marked EOL for Sever 2008, you may start seeing this issue with other things going forward.

**Comment by DanTheTechMan** [comment]
Ok. So, is there anything that can be done to get it working? I was able to use this successfully a month ago using Python2, before the script was migrated to Python3. The version of Python3 I'm using is the last one supported for Windows NT 6.1 based devices, so I should not be running into any issues. Also, I think it's worth noting that my OS is up to date as of October 13th (the October patch Tuesday), even though it's supposedly reached "EOL".

**Comment by DanTheTechMan** [comment]
After spending much of the day researching, I came across the following website which had the solution that worked for me:

https://stackoverflow.com/questions/35569042/ssl-certificate-verify-failed-with-python3


For those facing this same issue with the same or maybe similar setup to mine, here's the solution:

Simply go to the Python Install directory, then open the "Scripts" folder, open a command line window from the "Scripts" folder and run the following command:

pip install --upgrade certifi


That's it!
