### ISSUE TITLE
Docker container 0.5.3 - Unable to log in if password ends in !

### ISSUE THREAD

**Issue by azwildfire** [tgorgdotcom/locast2plex#119]
can repo and confirm - if password ends in a **!** you get a python error of an invalid function.

**Comment by azwildfire** [comment]
[https @ 0x555b2ee73880] HTTP error 428 Unknown
https://hls.locastnet.org/proxy/srte2b1/variant/330J3LE7jIQQIzu4CqakveP1BgbSwcfoYq0qkeVDqhG6xgVcjdWE1G1o8cIgnkfXKPuK0gStc58fYjKWCf6Juk14WjOPhyzs7NSmCyfW4TBo.m3u8: Server returned 4XX Client Error, but not one of 40{0,1,3,4}
ffmpeg version 4.0.6 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.0 (Alpine 9.3.0)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-fontconfig --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libbluray --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-libsrt --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[https @ 0x558a19494880] HTTP error 428 Unknown
https://hls.locastnet.org/proxy/srte2b1/variant/4qKZUJSdLR61ocpKLrk5aOY9juRppsrgd4XG5gqCqKNLYPysW3dPYt2AKcsKts9GmfOj94owYu0wP3YPbp74znC7B0pIlqWH3LdiJSvkEOzQ.m3u8: Server returned 4XX Client Error, but not one of 40{0,1,3,4}

**Comment by tgorgdotcom** [comment]
Hello all.  I think this should be fixed in 0.6.x.  Let me know if you're still running into issues.
