### ISSUE TITLE
No DMA to FCC mapping found

### ISSUE THREAD

**Issue by strid3r21** [tgorgdotcom/locast2plex#122]
locast just added indianapolis to their service area and so i think that maybe the issue here.

locast2plex spits out this error 

`Loading FCC Stations list...
No DMA to FCC mapping found. Poke the developer to get it into locast2plex.`

**Comment by deathbybandaid** [comment]
If you don't want to wait for @tgorgdotcom to add it, you can always modify the file locally. 

https://github.com/tgorgdotcom/locast2plex/blob/master/fcc_dma_markets.json

**Comment by strid3r21** [comment]
> If you don't want to wait for @tgorgdotcom to add it, you can always modify the file locally.
> 
> https://github.com/tgorgdotcom/locast2plex/blob/master/fcc_dma_markets.json

Unfortunately I'm using this on unraid and I'm not familiar with how I would go about updating this specific file on unraid. So hopefully the author is able to update it soon.

Thanks for your help tho!

**Comment by chris00780** [comment]
Indy is 527 for the DMA # if you figure out how to edit the file. I got it working on windows

**Comment by tgorgdotcom** [comment]
Mapping is now updated.  Sorry for the delay.  The next update *should* prevent issues like this from occurring in the future.

**Comment by strid3r21** [comment]
> Mapping is now updated. Sorry for the delay. The next update _should_ prevent issues like this from occurring in the future.

its working now! btw waiting a day is hardly a delay lol. thanks for all you do! we appreciate it.
