### ISSUE TITLE
Locast reports that this DMA\Market area is not currently active!

### ISSUE THREAD

**Issue by Teeko1993** [tgorgdotcom/locast2plex#126]
```
Locast2Plex v0.5.3
Tuner count set to 3
UUID set to: sljilwys...
Logging into Locast using username ******@gmail.com...
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 2020-11-17 19:58:43
Getting user location...
Getting location via IP Address.
Got external IP b'71.200.116.**'.
Got location as Wicomico - DMA 576 - Lat\Lon 38.3607\-75.5994
Locast reports that this DMA\Market area is not currently active!
Exiting...
```

Then repeats. If I go to the locast.org website using a browser, it correctly puts me in the Washington, DC DMA which is where I am. My ISP is Comcast. I thought maybe a way to geolocate other than an IP address? Not sure what the website uses but it seems to get it right.

**Comment by tgorgdotcom** [comment]
Check here: https://github.com/tgorgdotcom/locast2plex/issues/22#issuecomment-686237578

**Comment by Teeko1993** [comment]
Works perfectly. Thank you
