### ISSUE TITLE
No UUID found issue

### ISSUE THREAD

**Issue by chamby90** [tgorgdotcom/locast2plex#127]
v0.5.3 of locast2plex
Windows 10, Python v3.8 installed

I get the same error when trying to start locast2plex via terminal command line or docker:

**C:\locast2plex-master>python3 main.py
Locast2Plex v0.5.3
Tuner count set to 3
No UUID found.  Generating one now...
Traceback (most recent call last):
  File "main.py", line 368, in <module>
    config_handler.set('main', 'uuid', DEVICE_UUID)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\configparser.py", line 902, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'main'**

Ive tried to force a UUID in the main.py file... but my understanding of this error is that Locast cant find my location on my device.  I ensured that my location is turned on, so not what else I can do here?  Been stuck on this for a while now.  Any help is appreciated.

I can also launch Locast.org in a web browser and it can find my location seemingly fine.

thanks

**Comment by chamby90** [comment]
i see in a similar closed ticket - that this might solve the problem:
    **You have to mount the file instead of the folder. For instance:

    /mnt/cache/appdata/locast2plex/config.ini 
    Container path: /app/config.ini

_that fixed the problem thank you.**_

Can somebody tell me how to do that?  I have no idea what i am doing with docker.

**Comment by way3hosting** [comment]
I am getting a similar error, but am not using docker.

I have Plex running on 127.0.0.1 on a Windows 10 system.

When running the command in the cmd box (with administrative priviledges) I get:

```
c:\>c:\code\Python39\python.exe c:\code\locast2plex\main.py -u:email@address.com -p:XXXXXXXX --debug --addy:127.0.0.1 --port:6077
Locast2Plex v0.5.3
Tuner count set to 3
No UUID found.  Generating one now...
Traceback (most recent call last):
  File "c:\code\locast2plex\main.py", line 368, in <module>
    config_handler.set('main', 'uuid', DEVICE_UUID)
  File "c:\code\Python39\lib\configparser.py", line 902, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'main'
```

Any suggestions?

**Comment by deathbybandaid** [comment]
Use the config file instead of the commandline args

**Comment by way3hosting** [comment]
Thanks!

Can you head me in the direction on how that works?  What needs to be in the file and where it needs to be located?  Does it change the command line parameters?

**Comment by chamby90** [comment]
I'm kind of embarrassed to write this... but will incase this helps others who made my mistake.  When I saved the config file I literally saved it as "config.ini"  which means it was "config.ini.ini".    Once I simply saved the config file as "config"  it solved my issue.
