### ISSUE TITLE
Config parser not found

### ISSUE THREAD

**Issue by russdog75** [tgorgdotcom/locast2plex#130]
After upgrading from commandline driven older version, I'm getting this response when trying to start.

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    import configparser
ImportError: No module named configparser

What am I missing?

**Comment by deathbybandaid** [comment]
you using Py3?

**Comment by russdog75** [comment]
I wiped it and recloned it and it seems to have resolved.  Puzzled.
