### ISSUE TITLE
Error in /app/main.py

### ISSUE THREAD

**Issue by jasonrapps** [tgorgdotcom/locast2plex#14]
Just got locast in my area (Miami/FLL) and tried to run this...i will admit i'm a novice when it comes to docker so I may be doing this wrong, but I get an error in /app/main.py

Status: Downloaded newer image for tgorg/locast2plex:latest
Locast2Plex v0.4.1
DEBUG MODE ACTIVE
UUID found.
UUID set to: vjykylin...
Logging into Locast using username xxxx
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 1598989172
Getting user location...
User location obtained as 26.3165/-80.2748
Getting user's media market (DMA)...
DMA found as 528
Getting list of stations based on DMA...
Loading FCC Stations list...
Traceback (most recent call last):
  File "/app/main.py", line 324, in <module>
    station_list = locast.get_stations()
  File "/app/LocastService.py", line 195, in get_stations
    fcc_market = dma_mapping[str(self.current_dma)]
KeyError: '528'

**Comment by tgorgdotcom** [comment]
Hello.  That was my fault; I didn't add support for Miami and West Palm Beach.  I'm pushing a new version (0.4.2) with the support now.  If you could delete the image/container and start again that should fix your issues.  Thanks

**Comment by jasonrapps** [comment]
Works perfectly now! Thank you so much
