### ISSUE TITLE
Crash during EPG refresh during initial docker startup

### ISSUE THREAD

**Issue by jgshields50** [tgorgdotcom/locast2plex#151]
Trying to setup for first time.
Docker install starts and then crashes. See log:
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 2021-01-05 01:13:07
Starting First time Stations refresh...
Checking FCC facilities database for updates.
Online facilities database is newer. Downloading the latest FCC facilities database...
Unzipping FCC facilities database...
Reading and formatting FCC database...
Found 6616 stations.
Getting list of stations based on DMA...
Found 36 stations for DMA 524
Starting Stations thread...
Starting device server on 192.168.1.235:6077
Now listening for requests.
Starting SSDP server...
Starting First time EPG refresh...
Fetching:   https://api.locastnet.org/api/watch/epg/524?startTime=2020-12-05T00:00:00
Fetching:   https://api.locastnet.org/api/watch/epg/524?startTime=2020-12-06T00:00:00
Fetching:   https://api.locastnet.org/api/watch/epg/524?startTime=2020-12-07T00:00:00
Fetching:   https://api.locastnet.org/api/watch/epg/524?startTime=2020-12-08T00:00:00
Fetching:   https://api.locastnet.org/api/watch/epg/524?startTime=2020-12-09T00:00:00
Traceback (most recent call last):
  File "/app/main.py", line 84, in <module>
    epg2xml.generate_epg_file(config, location_info.location)
  File "/app/lib/epg2xml.py", line 120, in generate_epg_file
    channel_number = str(dma_channels[sid]['channel'])
KeyError: '1607038422937'

**Comment by arejay73** [comment]
I am seeing this as well.

**Comment by arejay73** [comment]
There must be something wrong with the Channels Database.  No my Docker is crashing on EPG refresh.  It initially said there are 34 station is my location, 524.  But when I run the raw command it show 37 and I see channels that are not in my market.

`curl -s https://api.locastnet.org/api/watch/epg/524?startTime=2020-12-09T00:00:00 | jq '.[] | .id' | sort -u | wc -l`

```
{
  "id": 1607038351043,
  "callSign": "16.1 BEINX"
}
{
  "id": 1607038384825,
  "callSign": "16.2 SONLIFE"
}
{
  "id": 1607038422937,
  "callSign": "16.3 WYGACD3"
}
```

The key error ID match channel - 16.3

**Comment by arejay73** [comment]
Looks like it is bad EPG data.  This station id is in the EPG, but maybe not on the station list.  It only seems to happen in Dec 9 date of the epg data pull.

`curl -s https://api.locastnet.org/api/watch/epg/524?startTime=2020-12-08T00:00:00 | jq '.[] | select(.id==1607038422937)'`
Not Results

```
curl -s https://api.locastnet.org/api/watch/epg/524?startTime=2020-12-09T00:00:00 | jq '.[] | select(.id==1607038422937)'
{
  "id": 1607038422937,
  "dma": 524,
  "stationId": "68572",
  "name": "WYGACD3",
  "callSign": "16.3 WYGACD3",
  "logoUrl": "https://fans.tmsimg.com/sources/generic/generic_sources_h3.png",
  "active": true,
  "listings": [],
  "sequence": 370,
  "logo226Url": "https://fans.tmsimg.com/sources/generic/generic_sources_h3.png"
}
```

`curl -s https://api.locastnet.org/api/watch/epg/524?startTime=2020-12-10T00:00:00 | jq '.[] | select(.id==1607038422937)'`
No Results

**Comment by arejay73** [comment]
I think this is also related to  #150

**Comment by arejay73** [comment]
This is still failing.  Any ideas on how to improve error checking for this condition?

**Comment by tgorgdotcom** [comment]
Hello.  Just pushed a new version (0.6.3) that should fix it.  Please check to see if that fixes the issue.

**Comment by diablc** [comment]
My issue is fixed.  Thanks!

**Comment by jgshields50** [comment]
My issue is fixed. Thank you!

**Comment by deathbybandaid** [comment]
@tgorgdotcom I've found it helps to hit `"https://api.locastnet.org/api/watch/epg/%s" % DMA` without the timestamps to fill in some epg data for some channels.
