### ISSUE TITLE
"Source is unavailable"

### ISSUE THREAD

**Issue by mbtfeedback** [tgorgdotcom/locast2plex#153]
Seems like Locast changed something on the backend in the last 24 hours. First I noticed I had to re-activate my Roku that has the Locast app on it. I immediately got suspicious, and sure enough, the Locast2Plex service was running just fine, but could not access Locast's streams. I tried re-creating the container which succeeded. When I run it, I see this appear over and over in the log as it tries to access a stream (I am in the Philadelphia market).

Opening 'https://phi.locastnet.org/proxy/phi/variant/4ouEELk5pVYcS5xfQYhQZwTsCRKgwFqmLcvyHJdcvMrtbrajWktKX5BGPCpZdy6APek0lOMXTY5fYaTQpRSrcqtV1zYALYgb1teP8CxUs4nb.m3u8' for reading

**Comment by CTJohnK** [comment]
Looks like it changed between 3am and 11am ET today, just checked and last successful recording completed at 3, next recording failed at 11.

**Comment by CTJohnK** [comment]
Seems like it is working again, 4:30 recording started fine.

**Comment by mbtfeedback** [comment]
No such luck here. Still no response.

**Comment by mbtfeedback** [comment]
And just to clarify, I have made zero configuration changes to my server or network. I can still access Locast via the web.

**Comment by mbtfeedback** [comment]
This is working again today.
