### ISSUE TITLE
Error during login

### ISSUE THREAD

**Issue by johnlago** [tgorgdotcom/locast2plex#16]
Hey, this looks amazing! But I'm having trouble logging into Locast. I get this error:

`Locast2Plex v0.4.2
DEBUG MODE ACTIVE
UUID found.
UUID set to: xxxx...
Logging into Locast using username xxxx@gmail.com...
Error during login: Not Found
Exiting...`

(Anonymized with `xxxx`)

Is this an issue on the Locast side? Seems like this might be a URL issue, peeking at the code.

**Comment by johnlago** [comment]
Aha - found the issue. Special characters in the password throw it for a loop. I had `#` and `$` in mine.

**Comment by tgorgdotcom** [comment]
Thanks for catching this!  How did you fix it?  Did you change your password or add a line to the code?

**Comment by FozzieBear** [comment]
Ran into the same issue here (via docker). If spinning it up via compose, single quoting the entire environment variable will work to escape the special characters. For example:
```    
    environment:
          - username=blah@email.com
          - 'password=cgnk96C6md&KV8!&XT9@G'
```
