### ISSUE TITLE
OSError: [WinError 10049] The requested address is not valid in its context

### ISSUE THREAD

**Issue by InchDeep** [tgorgdotcom/locast2plex#162]
I bought a Nvidia Shield TV device with the intent of running Plex Server on it and using Locast2Plex to feed the streams for storage on a connected USB hard drive.

The Shield powered up and got a DHCP address from the pool because I had not configured the MAC address with a reservation.

Installed Python v3.9.1 on an older desktop computer running Windows 10 Pro.
Installed the current Locast2Plex on the same desktop.
Edited the "configure.ini" file to point to the Shield device and with my locast credentials.
Everything worked (sweet!)

Then I created a reservation for the Shield with a different IP address (out of the pool).
Rebooted.
Edited the "configure.ini" file to point to the Shield device's new IP address.
Failed. (crap!)

I've tried uninstalling Python and deleting Locast2Plex, rebooting, reinstalling, etc.
I've tried installing Python and Locast2Plex on a different Windows 10 system.
I've tried reseting the Shield device to factory default.

None of the above has solved for this error message.  It is too vague for me to make much sense of it.  Can anyone shed some light on this?

```
Starting device server on 192.168.1.x:6077
Traceback (most recent call last):
  File "C:\locast2plex\main.py", line 75, in <module>
    tuner_interface.start(config, locast, location_info.location)
  File "C:\locast2plex\lib\tuner_interface.py", line 439, in start
    serverSocket.bind((config["main"]['bind_ip'], int(config["main"]['bind_port'])))
OSError: [WinError 10049] The requested address is not valid in its context

```

**Comment by CTJohnK** [comment]
Sorry to ask, but is 192.168.1.x you reference the IP address of the Shield or the old desktop?  It should be the old desktop running L2P.

**Comment by InchDeep** [comment]
Man, do I feel stupid.  How did I get that correct "out of the box" but jack it up the next day?   Grumble grumble grumble.

I was tempted to just not reply (and spare myself the embarrassment), but decided that I should help the next goofball that does the same thing.

Thanks, CTJohnK.  I'm going to go hide now.

**Comment by CTJohnK** [comment]
No problem.  Been there, done that - many times.
