### ISSUE TITLE
live tv pauses, then resumes where it left off every 10 seconds or so

### ISSUE THREAD

**Issue by scumola** [tgorgdotcom/locast2plex#19]
Running the latest python version (not the docker version).
ffmpeg version 2.8.11-0ubuntu0.16.04.1
I have a paid locast.org account.

If I stream the live stream through plex, the stream pauses every few seconds.  If I record a show, the video stream is clean with an almost imperceptible audio dip every 10 seconds or so - which is very watchable.  Output from the tool looks like:

127.0.0.1 - - [09/Aug/2020 16:05:00] "GET /discover.json HTTP/1.0" 200 -.0kbits/s    
127.0.0.1 - - [09/Aug/2020 16:05:00] "GET /lineup_status.json HTTP/1.0" 200 -
[https @ 0xff35c0] No trailing CRLF found in HTTP header.
[https @ 0x13de3c0] No trailing CRLF found in HTTP header.1 bitrate= 734.1kbits/s    
[https @ 0x1dbe6c0] No trailing CRLF found in HTTP header.
127.0.0.1 - - [09/Aug/2020 16:05:10] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Aug/2020 16:05:10] "GET /lineup_status.json HTTP/1.0" 200 -
[https @ 0x1dbe6c0] No trailing CRLF found in HTTP header.1 bitrate=1106.8kbits/s    
[https @ 0x18fbb20] No trailing CRLF found in HTTP header.
127.0.0.1 - - [09/Aug/2020 16:05:20] "GET /discover.json HTTP/1.0" 200 -.4kbits/s    
127.0.0.1 - - [09/Aug/2020 16:05:20] "GET /lineup_status.json HTTP/1.0" 200 -
[https @ 0x14a9a60] No trailing CRLF found in HTTP header.0 bitrate= 764.0kbits/s    
127.0.0.1 - - [09/Aug/2020 16:05:30] "GET /discover.json HTTP/1.0" 200 -.4kbits/s    
127.0.0.1 - - [09/Aug/2020 16:05:30] "GET /lineup_status.json HTTP/1.0" 200 -
[https @ 0x1919d20] No trailing CRLF found in HTTP header.
[https @ 0xff35c0] No trailing CRLF found in HTTP header.00 bitrate= 766.7kbits/s    
[https @ 0x14a9a60] No trailing CRLF found in HTTP header.
127.0.0.1 - - [09/Aug/2020 16:05:40] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [09/Aug/2020 16:05:40] "GET /lineup_status.json HTTP/1.0" 200 -
[https @ 0x14ae560] No trailing CRLF found in HTTP header.0 bitrate=1095.8kbits/s    
[https @ 0xff35c0] No trailing CRLF found in HTTP header.

Not sure if the "no trailing CRLF found in header" message is just a warning or not.

I can try the docker version to see if it's a python library or ffmpeg or something else that's not happy.

**Comment by scumola** [comment]
Just an update, the docker container seems to have the same issue when streaming live for the first couple of minutes, then it seems to catch up and stream ok.  I'll continue to play with it.  CPU, ram and disk seem to be plenty abundant, so it's not a resource issue.  I've got Gigabit fibre to my plex server, so network isn't an issue.

**Comment by tgorgdotcom** [comment]
Hello.  A few questions:

 - Is locast2plex on the same server as the Plex server?
 - Does the Plex client connect to the server via wire or wireless?

There's one thing we can try as well, but let's start at gathering some information.
