### ISSUE TITLE
FCC moved to https://

### ISSUE THREAD

**Issue by ThomasPBrauer** [tgorgdotcom/locast2plex#194]
facility_url = 'http**s**://transition.fcc.gov/ftp/Bureaus/MB/Databases/cdbs/facility.zip'

**Comment by tgorgdotcom** [comment]
Added to codebase.  Thanks!

**Comment by enishoca** [comment]
Is this in the docker image yet?

**Comment by tgorgdotcom** [comment]
Yup, it's live
