### ISSUE TITLE
Remote end closed connection without response

### ISSUE THREAD

**Issue by perci96** [tgorgdotcom/locast2plex#200]
Hello everyone. 
I am a new user and have been successfully running locast2plex since November until yesterday when my I started seeing errors even though I made no updates. I uninstalled/reinstalled according to the instructions and am still getting a “Remote end closed connection without response” error.
I’m using docker on Windows 10 and have downloaded the latest files (https://github.com/tgorgdotcom/locast2plex) for my install, but I’m still receiving a time-out error. 
Apologies if I’m missing any information on this request and will gladly forward whatever is needed to research this issue. This service works GREAT and I appreciate everyone’s work on getting this running! Thanks in advance for any suggestions!

locast2plex_1 | Initiating Locast2Plex v0.6.2
locast2plex_1 | Opening and Verifying Configuration File.
locast2plex_1 | /app/config/config.ini
locast2plex_1 | Loading Configuration File: /app/config/config.ini
locast2plex_1 | Tuner count set to 3
locast2plex_1 | Server is set to run on 192.168.1.96:6077
locast2plex_1 | UUID set to: iujntwtk...
locast2plex_1 | Getting user location...
locast2plex_1 | Getting location via IP Address.
locast2plex_1 | Got external IP 97.70.66.218.
locast2plex_1 | Got location as Detroit - DMA 505 - Lat\Lon 42.5051\-83.4072
locast2plex_1 | Logging into Locast using username ZZZZZZZ@yahoo.com...
locast2plex_1 | Validating User Info...
locast2plex_1 | User Info obtained.
locast2plex_1 | User didDonate: True
locast2plex_1 | User donationExpire: 2021-03-10 17:18:53
locast2plex_1 | Starting First time Stations refresh...
locast2plex_1 | Checking FCC facilities database for updates.
locast2plex_1 | Traceback (most recent call last):
locast2plex_1 | File "/app/main.py", line 67, in <module>
locast2plex_1 | stations.refresh_dma_stations_and_channels(config, locast, location_info.location)
locast2plex_1 | File "/app/lib/stations.py", line 38, in refresh_dma_stations_and_channels
locast2plex_1 | fcc_stations = get_fcc_stations(config)
locast2plex_1 | File "/app/lib/stations.py", line 144, in get_fcc_stations
locast2plex_1 | online_file_time = get_online_file_time(facility_url)
locast2plex_1 | File "/app/lib/stations.py", line 44, in get_online_file_time
locast2plex_1 | resp = urllib.request.urlopen(url_head)
locast2plex_1 | File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
locast2plex_1 | return opener.open(url, data, timeout)
locast2plex_1 | File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
locast2plex_1 | response = self._open(req, data)
locast2plex_1 | File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
locast2plex_1 | result = self._call_chain(self.handle_open, protocol, protocol +
locast2plex_1 | File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
locast2plex_1 | result = func(*args)
locast2plex_1 | File "/usr/local/lib/python3.8/urllib/request.py", line 1379, in http_open
locast2plex_1 | return self.do_open(http.client.HTTPConnection, req)
locast2plex_1 | File "/usr/local/lib/python3.8/urllib/request.py", line 1354, in do_open
locast2plex_1 | r = h.getresponse()
locast2plex_1 | File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
locast2plex_1 | response.begin()
locast2plex_1 | File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
locast2plex_1 | version, status, reason = self._read_status()
locast2plex_1 | File "/usr/local/lib/python3.8/http/client.py", line 276, in _read_status
locast2plex_1 | raise RemoteDisconnected("Remote end closed connection without"
locast2plex_1 | http.client.RemoteDisconnected: Remote end closed connection without response
locast2plex-main_locast2plex_1 exited with code 1

**Comment by tgorgdotcom** [comment]
Hello @perci96.  Try upgrading to v0.6.5 to see if that resolves your problem

**Comment by perci96** [comment]
Thank you very much for the reply. I installed 0.6.5 (https://github.com/tgorgdotcom/locast2plex/archive/0.6.5.zip) and am receiving the same error. Strange thing is the locast2plex-065 container toggles back and forth from “running” to “other” which is suggesting it’s about to complete the connection using “docker-compose up”, but it ultimately fails with the “Remote end closed connection without response”.   Thanks again in advance for any assistance! :)
 

locast2plex_1  | Initiating Locast2Plex v0.6.2
locast2plex_1  | Opening and Verifying Configuration File.
locast2plex_1  | /app/config/config.ini
locast2plex_1  | Loading Configuration File: /app/config/config.ini
locast2plex_1  | Tuner count set to 3
locast2plex_1  | Server is set to run on  127.0.0.1:6077
locast2plex_1  | UUID set to: oplrjwux...
locast2plex_1  | Getting user location...
locast2plex_1  | Getting location via IP Address.
locast2plex_1  | Got external IP 97.70.66.218.
locast2plex_1  | Got location as Detroit - DMA 505 - Lat\Lon 42.5051\-83.4072
locast2plex_1  | Logging into Locast using username XXXXXXX@yahoo.com...
locast2plex_1  | Validating User Info...
locast2plex_1  | User Info obtained.
locast2plex_1  | User didDonate: True
locast2plex_1  | User donationExpire: 2021-03-10 17:18:53
locast2plex_1  | Starting First time Stations refresh...
locast2plex_1  | Checking FCC facilities database for updates.
locast2plex_1  | Traceback (most recent call last):
locast2plex_1  |   File "/app/main.py", line 67, in <module>
locast2plex_1  |     stations.refresh_dma_stations_and_channels(config, locast, location_info.location)
locast2plex_1  |   File "/app/lib/stations.py", line 38, in refresh_dma_stations_and_channels
locast2plex_1  |     fcc_stations = get_fcc_stations(config)
locast2plex_1  |   File "/app/lib/stations.py", line 144, in get_fcc_stations
locast2plex_1  |     online_file_time = get_online_file_time(facility_url)
locast2plex_1  |   File "/app/lib/stations.py", line 44, in get_online_file_time
locast2plex_1  |     resp = urllib.request.urlopen(url_head)
locast2plex_1  |   File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
locast2plex_1  |     return opener.open(url, data, timeout)
locast2plex_1  |   File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
locast2plex_1  |     response = self._open(req, data)
locast2plex_1  |   File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
locast2plex_1  |     result = self._call_chain(self.handle_open, protocol, protocol +
locast2plex_1  |   File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
locast2plex_1  |     result = func(*args)
locast2plex_1  |   File "/usr/local/lib/python3.8/urllib/request.py", line 1379, in http_open
locast2plex_1  |     return self.do_open(http.client.HTTPConnection, req)
locast2plex_1  |   File "/usr/local/lib/python3.8/urllib/request.py", line 1354, in do_open
locast2plex_1  |     r = h.getresponse()
locast2plex_1  |   File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
locast2plex_1  |     response.begin()
locast2plex_1  |   File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
locast2plex_1  |     version, status, reason = self._read_status()
locast2plex_1  |   File "/usr/local/lib/python3.8/http/client.py", line 276, in _read_status
locast2plex_1  |     raise RemoteDisconnected("Remote end closed connection without"
locast2plex_1  | http.client.RemoteDisconnected: Remote end closed connection without response
locast2plex-065_locast2plex_1 exited with code 1

**Comment by perci96** [comment]
Decided to try the Command line installation to bypass Docker and got it working. Needed to install Python 3.9 for Windows 10 first and ran the "python3 main.py" command in the install folder and I'm now all set.
