### ISSUE TITLE
Wrong Location Based On IP

### ISSUE THREAD

**Issue by doughnet** [tgorgdotcom/locast2plex#221]
Howdy!

I updated to latest version (6.5)

Since a few weeks ago it pulls up my IP and says it's from Seattle instead of SF Bay Area.  Via the desktop browser (from same IP) it shows as San Francisco on locast.org but when using the locast2plex application it says that same IP is from Seattle.

How do I resolve this?

**Comment by zach78954** [comment]
Please look at the wiki, specifically [Here ](https://github.com/tgorgdotcom/locast2plex/wiki/Troubleshooting-and-Common-Issues#locast2plex-does-not-detect-your-location-properly)

**Comment by doughnet** [comment]
thanks.  didnt see that in the wiki.
