### ISSUE TITLE
ffmpeg stuttering on HLS stream from locast

### ISSUE THREAD

**Issue by scumola** [tgorgdotcom/locast2plex#23]
Been using it for a few weeks now.  Very flakey.  Sometimes recordings only have 1 or 2 seconds in them.  Weird.

```
-rw-r--r-- 1 plex plex 69922276 Aug 14 16:54 According to Jim (2001) - S05E01 - Foul Ball.ts
-rw-r--r-- 1 plex plex   100392 Aug 15 21:30 According to Jim (2001) - S05E02 - The Tale of the Tape.ts
-rw-r--r-- 1 plex plex 34206036 Aug 14 22:13 According to Jim (2001) - S05E03 - The Tale of the Tape.ts
-rw-r--r-- 1 plex plex 30174188 Aug 14 21:59 According to Jim (2001) - S05E04 - Charity Begins at Hef's.ts
-rw-r--r-- 1 plex plex    96820 Aug 15 22:30 According to Jim (2001) - S05E05 - The Race.ts
-rw-r--r-- 1 plex plex 26383732 Aug 14 23:59 According to Jim (2001) - S05E06 - Anec-Don'ts.ts
-rw-r--r-- 1 plex plex   168448 Aug 16 22:05 According to Jim (2001) - S05E08 - James and the Annoying Peach.ts
-rw-r--r-- 1 plex plex    57152 Aug 16 23:05 According to Jim (2001) - S05E10 - Lean on Me.ts
```

**Comment by scumola** [comment]
I don't have any other DVR settings on, like auto-detect commercials or anything.

**Comment by scumola** [comment]
I'm seeing this in the logs:

```
[https @ 0xf9a2c0] No trailing CRLF found in HTTP header.
Traceback (most recent call last):   565kB time=00:22:32.51 bitrate=   3.4kbits/s    
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

**Comment by scumola** [comment]
Ok, just streaming using ffmpeg to VLC, I'm getting some stuttering (stream comes and goes every few seconds).

```
ffmpeg -i https://den.locastnet.org/proxy/den/variant/CaFN4Zc18XUQXnpmiyXu42czWjcqf5AgEvrbmBWFWhp8d1QGNmjbtiG9SkkI2G0dDOMqXhCjT9gks3dptwRiAi.m3u8 -codec copy -f mpegts  udp://10.0.0.37:1234
```
So it looks like my issue is ffmpeg.  When pasting that same url into VLC directly, things stream properly, so my issue is with ffmpeg.  I'll try to work those out and get back to you.  :)

**Comment by scumola** [comment]
Tried ffmpeg on a more modern ubuntu distro on a different machine with the same stuttering issue.
ffplay with the source m3u8 url, works great.
VLC with the source m3u8 url, works great.
Tried the latest stable 64-bit binary from the official ffmpeg page.  Same stuttering issue.

There's something about ffmpeg that causes the stuttering issue for me.  When switching from one HLS stream to the next, ffmpeg occasionally causes a stutter and I can't really get around it.

**Comment by tgorgdotcom** [comment]
Is VLC and ffmpeg/locast2plex running on the same machine?  I'm starting to think that maybe there's some adjustments that need to be made as to how much video data at a time I receive from Locast, perhaps in particular for fast connections.

**Comment by scumola** [comment]
There is a way to use vlc to stream to stdout instead of using ffmpeg.  Maybe replace the ffmpeg line to use vlc?
I'm not able to test at this time (I filed a new bug and the client never seems to call /watch anymore for some reason, uugh), but perhaps this could be tried?

`ffmpeg_proc = subprocess.Popen(["/usr/bin/vlc", "-I", "dummy", channelUri, "--sout", "#std{mux=ts,access=file,dst=-}"], stdout=subprocess.PIPE)`

**Comment by scumola** [comment]
Going to close this issue now too.  Running the docker container using my docker host's IP address (instead of 0.0.0.0) seems to be working for me.  The stream seems to be pretty solid, so I figure this problem is mute.  :)  Thanks for the great work, BTW.
