### ISSUE TITLE
Recorded Resolution

### ISSUE THREAD

**Issue by KBoz** [tgorgdotcom/locast2plex#265]
I've had Locast2Ples working for a while now and recorded a few programs on a variety of channels.  Although the recordings seem to accurately reflect the broadcast resolution of some lower resolution channels when I display content in Plex records from CBS or PBS (1080i) all episodes and shows indicate the recording is in 720p.

Locast says they do not adjust the native broadcast resolution.  Is that an error in what Plex shows or is Locast2Plex altering the resolution?

**Comment by rocky4546** [comment]
Locast does adjust the frame rate and the resolution for those that are not 480p.  I have a number of 1080 channels that locast broadcasts at 720.  Also, 720 channels at 60fps that locast broadcasts at lower fps.  I use HDHomerun with an antenna to see what is broadcast versus what locast provides.

**Comment by KBoz** [comment]
Interesting.  Locast says on their web site that they provide original broadcast quality.  Wonder how that will work now that stations are rolling out ATSC 3.
