### ISSUE TITLE
Docker Container Stuck Restarting

### ISSUE THREAD

**Issue by RedGreen007** [tgorgdotcom/locast2plex#27]
I am attempting to install this on my Plex machine which currently is running Ubuntu 20.04 server.

I got Docker installed and updated. 

Have the correct version of Python and FFMPEG installed.

I edited the docker-compose.yml to look like the following.

locast2plex:
    image: tgorg/locast2plex
    ports:
      - "${external_port}:6077"
    restart: unless-stopped
    environment:
      - username='USERNAME'
      - password='PASSWORD'
      - external_addy='127.0.0.1'
      - external_port='1234'
      - debug

Save that file. Then run docker-compose -up. It creates the image and then when I go to run the container ID. It just says restarting. 

Where is my dumb ass failing? Cause this is my first time trying out Docker hahahaha

**Comment by RedGreen007** [comment]
It says this when I try and build the container.


locast2plex_1  | Locast2Plex v0.4.2
locast2plex_1  | DEBUG MODE ACTIVE
locast2plex_1  | UUID found.
locast2plex_1  | UUID set to: lrtrvhsi...
locast2plex_1  | Logging into Locast using username "royce.schnepp@gmail.com"...
locast2plex_1  | Error during login: Bad Request
locast2plex_1  | Exiting...

**Comment by tgorgdotcom** [comment]
Hmmm, I think you might need to remove the quotes around the username/password.  If your password has special characters, put the quotes around the entire `password=PASSWORD` line, like `- 'password=1234'`.  Hope that helps!

**Comment by RedGreen007** [comment]
I tried that and now it says login not found.


redgreen@tortuga:~/locast2plex$ docker-compose up
WARNING: The F variable is not set. Defaulting to a blank string.
Recreating locast2plex_locast2plex_1 ... done
Attaching to locast2plex_locast2plex_1
locast2plex_1  | Locast2Plex v0.4.2
locast2plex_1  | DEBUG MODE ACTIVE
locast2plex_1  | UUID found.
locast2plex_1  | UUID set to: lrtrvhsi...
locast2plex_1  | Logging into Locast using username royce.schnepp@gmail.com...
locast2plex_1  | Error during login: Not Found
locast2plex_1  | Exiting...

**Comment by RedGreen007** [comment]
It's trying, but for some reason just won't accept the username.

**Comment by RedGreen007** [comment]
locast2plex_1  | Locast2Plex v0.4.2
locast2plex_1  | DEBUG MODE ACTIVE
locast2plex_1  | UUID found.
locast2plex_1  | UUID set to: lrtrvhsi...
locast2plex_1  | Logging into Locast using username royce.schnepp@gmail.com...
locast2plex_1  | Validating User Info...
locast2plex_1  | User Info obtained.
locast2plex_1  | User didDonate: False
locast2plex_1  | Traceback (most recent call last):
locast2plex_1  |   File "/app/main.py", line 320, in <module>
locast2plex_1  |     if (not locast.login(CONFIG_LOCAST_USERNAME, CONFIG_LOCAST_PASSWORD)) or (not locast.validate_user()):
locast2plex_1  |   File "/app/LocastService.py", line 85, in validate_user
locast2plex_1  |     print("User donationExpire: " + str(userRes['donationExpire'] / 1000))
locast2plex_1  | TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

**Comment by tgorgdotcom** [comment]
Looks like my check for donation is failing, but in any event, are you using a Locast account that has donated?

**Comment by RedGreen007** [comment]
I have not yet. That was going to be my next question was does it require it? I was going to test it out first and then donate if I could get it working. But if the check needs it for 5 bucks to try it for a month isn't a big deal.

**Comment by tgorgdotcom** [comment]
Unfortunately, yes.  I do that because there would be issues in using DVR for non-donating users (as the stream would be cut off after 15 mins)

**Comment by RedGreen007** [comment]
I will subscribe then and give it a shot again. I will close this out since its clear its not you...its me :p
