### ISSUE TITLE
Channel scan fails

### ISSUE THREAD

**Issue by endquote** [tgorgdotcom/locast2plex#277]
I can run locast2plex, and Plex auto-discovers it as a tuner, but I can't scan for channels. I see a request for `/devices/nljopryy/scan?provider=1` but it returns a 501 error. It has worked in the past... but not lately.

![Screen Shot 2021-08-05 at 7 27 16 PM](https://user-images.githubusercontent.com/330010/128446825-abc119ff-2124-4331-83cb-c44f56120bfe.png)

![Screen Shot 2021-08-05 at 7 27 26 PM](https://user-images.githubusercontent.com/330010/128446822-4d261280-d9ec-40c7-8778-54e3c7767591.png)

**Comment by jwarner75** [comment]
Try manually adding in the IP Address along with the Port to add in the Tuner then scan the Channels.

Some other people have been having some issues with Discovery of the tuners and not being able to scan for channels.

Before the files were updated on the scripts, I had to remove my DVR tuners and add them back. They wouldn't auto find them so I manually entered in the IP Address along with the Port number (192.168.1.xxx:6077) like so, It found them, Scanned the channels and worked fine it seems so far.

**Comment by endquote** [comment]
I think that worked. If I add it manually I end up with a "tuner" and a "network" device, and the "tuner" one works.

![Screen Shot 2021-08-06 at 10 02 03 AM](https://user-images.githubusercontent.com/330010/128546619-b26c97b2-71fc-4a9a-abbd-1b1edd4a43d5.png)

**Comment by jwarner75** [comment]
@endquote Awesome.

I have the script running on 2 computers, so I got 2 tuners added to my Plex Server and each tuner has 4 tuners not 3!
