### ISSUE TITLE
Error during geo IP acquisition: [Error 99] Address not available

### ISSUE THREAD

**Issue by gohanshadow** [tgorgdotcom/locast2plex#28]
Hello, I just setup locast2plex and continue getting this error on startup. Any assistance would be great. I'm using a Synology NAS with Docker installed.

```
Locast2Plex v0.4.2
DEBUG MODE ACTIVE
UUID found.
UUID set to: lrtrvhsi...
Logging into Locast using username xxxxx@domain.com...
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 1599581940
Getting user location...
Error during geo IP acquisition: [Errno 99] Address not available
Exiting...
```

Settings are
```
services:
  locast2plex:
    image: tgorg/locast2plex
    container_name: locast2plex
    ports:
      - "6077:6077"
    restart: unless-stopped
    environment:
      - username=xxxxx@domain.com
      - password=XXXXX
      - external_addy=192.168.10.XX
      - external_port=6077
      - debug=yes
```

I'll continue to see if I can figure it out but any help would be great. Thanks.

**Comment by tgorgdotcom** [comment]
Hmmmm,  it doesn't seem to like connecting to the GeoIP service.  I tried the script again from my end and had no issues.  Would you be able to try again and check if you're getting the same issue?  Thanks!

**Comment by gohanshadow** [comment]
I deleted the docker. Removed the image, redownloaded and setup again. I used the following settings again.

```
services:
  locast2plex1:
    image: tgorg/locast2plex
    container_name: locast2plex
    ports:
      - "6077:6077"
    restart: unless-stopped
    environment:
      - username=xxxxx@domain.com
      - password=XXXXX
      - external_addy=192.168.10.XX
      - external_port=6077
      - debug=yes
```

This is from the log on startup. 
```
Locast2Plex v0.4.2
DEBUG MODE ACTIVE
UUID found.
UUID set to: hmwhuwux...
Logging into Locast using username vphilip@gmail.com...
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 1599581940
Getting user location...
Error during geo IP acquisition: [Errno 99] Address not available
Exiting..
```

When I open the docker (I'm doing this through the GUI), I'm showing that the **Execution Command:** is `python /app/main.py 2>&1`. I just want to validate that is correct and if not, how to fix that?

**Comment by tgorgdotcom** [comment]
The execution command should be correct.  This is really strange.  If you can, from a terminal, run the following and get me the output:

`ping -c 5 get.geojs.io`

Thanks!

**Comment by gconcepts** [comment]
I'm having the same problem on a Synology NAS. 
The container dies before being able to access the terminal. But I accessed another container running on the same NAS and ran the command "ping -c 5 get.geojs.io". 
This comes back with a loopback IP of 127.0.0.1. I believe this is the issue as the geolocation isn't able to be passed to locast.org

**Comment by gohanshadow** [comment]
Hello, as mentioned by gconcepts, the container dies before being able to access terminal. I launched a separate container and tried the command and received the same output. I've added that to this post.

```
root@linuxserver-sickchill:/# ping -c 5 get.geojs.io                                        
PING get.geojs.io (0.0.0.0): 56 data bytes                                                  
64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.061 ms                                         
64 bytes from 127.0.0.1: seq=1 ttl=64 time=0.103 ms                                         
64 bytes from 127.0.0.1: seq=2 ttl=64 time=0.097 ms                                         
64 bytes from 127.0.0.1: seq=3 ttl=64 time=0.078 ms                                         
64 bytes from 127.0.0.1: seq=4 ttl=64 time=0.102 ms                                         
                                                                                            
--- get.geojs.io ping statistics ---                                                        
5 packets transmitted, 5 packets received, 0% packet loss                                   
round-trip min/avg/max = 0.061/0.088/0.103 ms  
```

I opened a browser and went to that site and it worked without any issue from my local machine.

Thanks again for any help.

**Comment by RedGreen007** [comment]
I too, am getting this error. I have donated since finding out I need to hahaha 

locast2plex_1  | Locast2Plex v0.4.2
locast2plex_1  | DEBUG MODE ACTIVE
locast2plex_1  | UUID found.
locast2plex_1  | UUID set to: lrtrvhsi...
locast2plex_1  | Logging into Locast using username XXXX@domain.com...
locast2plex_1  | Validating User Info...
locast2plex_1  | User Info obtained.
locast2plex_1  | User didDonate: True
locast2plex_1  | User donationExpire: 1600629887
locast2plex_1  | Getting user location...
locast2plex_1  | Error during geo IP acquisition: [Errno 99] Address not available
locast2plex_1  | Exiting...

**Comment by gohanshadow** [comment]
> I don't know how many of you are using pihole or something similiar for ad/domain blocking, but whitelisting the get.geojs.io fixed this issue for me.
By  @borfsu from issue #22 

This solved my issue somehow. Not sure why my docker can get to it now after whitelisting this, even after my laptop was able to get there the other day.... but it’s working now. 

Thanks so much

**Comment by tgorgdotcom** [comment]
I have left another comment on issue #22 about fixing location errors as well.  I'll close this one out and if you have any additional problems feel free to open another issue.
