### ISSUE TITLE
Playback Error: Source is unavailable

### ISSUE THREAD

**Issue by donomatic** [tgorgdotcom/locast2plex#292]
New install on Windows 10. There are no errors in cmd window but I get Source is unavailable on every channel.

Getting station info for 1572389490750...
Determining best video stream for 1572389490750...
Found 3 Playlists
1572389490750 will use 1280x720 resolution at 2700000bps
10.1.1.40 - - [27/Aug/2021 17:43:48] "GET /watch/1572389490750 HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:43:52] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:43:52] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:43:58] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:43:58] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:03] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:03] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:08] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:08] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:14] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:14] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:19] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:19] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:24] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:24] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:30] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:30] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:35] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:35] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:40] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:40] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:45] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:45] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:51] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:51] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:56] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:44:56] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:01] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:01] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:07] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:07] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:12] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:12] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:17] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:17] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:23] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:23] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:28] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:28] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:33] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:33] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:39] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:39] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:44] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:44] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:49] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:49] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:54] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:45:54] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:00] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:00] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:05] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:05] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:10] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:10] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:16] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:16] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:21] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:21] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:26] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:26] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:31] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:31] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:37] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:37] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:42] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:42] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:47] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:47] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:50] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:50] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:56] "GET /discover.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:56] "GET /lineup_status.json HTTP/1.1" 200 -
10.1.1.40 - - [27/Aug/2021 17:46:56] "GET /lineup.json HTTP/1.1" 200 -

**Comment by lewjh14** [comment]
Same issue with a new install on Synology DSM docker. I had login issues originally but the latest version fixed that. Unable to stream any channel now.

**Comment by donomatic** [comment]
I actually installed this in Docker on DSM and got the same error in Plex. I ended up doing a full uninstall of Plex (uninstalled PMS, all Plex folders in AppData and all Plex Registry keys). After that it is working great. Ended up not being related to this script.
