### ISSUE TITLE
Remove donor requirement

### ISSUE THREAD

**Issue by eabugda** [tgorgdotcom/locast2plex#299]
Now that Locast has removed the periodic donation request screen/interrupt (as a result of their recent court rulings) for non-donating users, can this restriction be removed from Locast2Plex?

**Comment by hifihedgehog** [comment]
If he doesn't accept my push request, it is easy enough for you to fix in the code. Remove lines 82-93 from locast_service.py. This removes the donor check. :)

**Comment by fkick** [comment]
@hifihedgehog I've tried removing lines 82-93 from locust_service.py, and while the docker does start up and load a guide, I'm unable to tune to a channel. 

I get the error "Could Not tune channel. Please check tuner or antenna. Code 5000".

Looking at the container logs I'm seeing:
```
[01/Sep/2021 23:56:10] "GET /discover.json HTTP/1.1" 200 -
[01/Sep/2021 23:56:10] "GET /lineup_status.json HTTP/1.1" 200 -
```

**Comment by hifihedgehog** [comment]
> @hifihedgehog I've tried removing lines 82-93 from locust_service.py, and while the docker does start up and load a guide, I'm unable to tune to a channel.
> 
> I get the error "Could Not tune channel. Please check tuner or antenna. Code 5000".
> 
> Looking at the container logs I'm seeing:
> 
> ```
> [01/Sep/2021 23:56:10] "GET /discover.json HTTP/1.1" 200 -
> [01/Sep/2021 23:56:10] "GET /lineup_status.json HTTP/1.1" 200 -
> ```

I am sorry it isn't working for you. Are you new to locast2plex? I am using locast2plex for the first time with a free subscriber account, and I had zero issues. To do this, you just need the latest stable code, and then you remove the lines checking for the subscriber status. Did you put the correct IP and port in Plex? The container is getting HTTP 200 codes, which means it is connected successfully to Locast. That to me sounds awfully a lot like a configuration issue in Plex, not a problem with locast2plex.

**Comment by fkick** [comment]
Thanks, I'm wondering if the XMLTV value is wrong in the plex setup, I'm using http://[IP]:6077/xmltv.xml where IP is the address of the Locast2Plex instance.

**Comment by fkick** [comment]
And I see that they've suspended operations, so that could be why I'm still seeing issues. NM

**Comment by hifihedgehog** [comment]
Feel free to close this ticket. Locast is dead. :(
