### ISSUE TITLE
Locast2Plex as a Windows Service is working great!

### ISSUE THREAD

**Issue by tharris9d** [tgorgdotcom/locast2plex#33]
I wanted to share how to setup Locast2Plex as a windows service. 
Why do it?
1. It automatically loads on reboot.
2. When updates are made to the py scripts I just have to restart the service.
3. I don't have a windows command window open. (I am not using Docker because it doesn't run as well! Less pausing and much faster loading from the command-line)
Download the totally FREE Non-Sucking Windows Service https://nssm.cc/download, Grab the prelease build 2.2.4-101 listed in the first sentence of the download page.
Unzip and Copy the win64/nssm.exe to the root of C:\ (or other folder of your preference)

from an elevated (Run as Administrator) command line type **c:\nssm.exe install locast2plex**
A GUI will popup

![image](https://user-images.githubusercontent.com/217445/90568822-7e951c00-e161-11ea-84a9-d876ae2928ab.png)

Here is what I filled in to the GUI
path: C:\Python27\Python27.exe
Startup directory: C:\Python27

Arguments: C:\code\locast2plex\main.py -u:usernamexxx -p:passwordxxx --debug --addy:127.0.0.1 --port:6077
Service name is locast2plex

Click Install Service.

Go to Run, services.msc, find locast2plex, set the service to run automatically and to start it.
Let me know if you need any help. 
It is running nicely for me. I rebooted to test it out and I am very pleased.

**Comment by tgorgdotcom** [comment]
Pinned, and I'll place a link in the wiki.

**Comment by tgorgdotcom** [comment]
Note: moved this to a wiki page, as there is a limit to 3 pins on the issues section.
