### ISSUE TITLE
Cannot Start Streams

### ISSUE THREAD

**Issue by pedwards3x** [tgorgdotcom/locast2plex#37]
I have the service up and running and I was able to add everything to the Plex server, but when I try to start a stream I get an error in Plex: "Could not tune channel. Please check your tuner or antenna." The logs on the service show the following:

XX.XX.XXX.XXX- - [19/Aug/2020 10:53:13] "GET /discover.json HTTP/1.0" 200 -
XX.XX.XXX.XXX - - [19/Aug/2020 10:53:13] "GET /lineup_status.json HTTP/1.0" 200 -
XX.XX.XXX.XXX - - [19/Aug/2020 10:53:20] "GET /lineup.json HTTP/1.0" 200 -
XX.XX.XXX.XXX - - [19/Aug/2020 10:53:20] "GET /discover.json HTTP/1.0" 200 -
XX.XX.XXX.XXX - - [19/Aug/2020 10:53:20] "GET /lineup_status.json HTTP/1.0" 200 -

**Comment by K0DCM** [comment]
I am getting the same error with windows 10  python 2.7 no channels will stream, playback error?

**Comment by jakewaldron** [comment]
I had this same issue setting it up just now in a freenas jail and fixed it by changing the --addy param from --addy=127.0.0.1 to the static IP of the jail: --addy=192.168.1.xxx

**Comment by pedwards3x** [comment]
So I got this fixed. I am using a DNS name to resolve to my server that is running the locast2plex service, so I had to use that in the --addy parameter. For example I could not use 127.0.0.1 but had to use "--addy domain.name.com" and now everything is streaming with no issues. Thanks!
