### ISSUE TITLE
error with code? something to do with dma??

### ISSUE THREAD

**Issue by ayumifanshawn** [tgorgdotcom/locast2plex#45]
pleas see attached picture of error i have no idea where to go.
![118269737_346199423433307_3400104566040205536_n](https://user-images.githubusercontent.com/70107567/90984488-4c116780-e543-11ea-8275-7df60c9ba8f9.jpg)

**Comment by CTJohnK** [comment]
You are appearing as DMA 592 which is the Gainesville, FL market and according to https://www.locast.org/dma, they only support Tampa-St. Pete (539), West Palm Beach-Ft.Pierce (548) and Miami-Ft.Lauderdale (528) currently.

Which market are you expecting to be within?

**Comment by ayumifanshawn** [comment]
this issue was corrected by contacting my isp they were able to change my dma to reflect my actual location

**Comment by tgorgdotcom** [comment]
Cool.  Marking as closed.
