### ISSUE TITLE
Locast2Plex w/cli on same windows (10) server as Plex.  "Device not found"

### ISSUE THREAD

**Issue by BH000** [tgorgdotcom/locast2plex#46]
The subject says most of it.  I've installed python 2.7* and L2P on the same Windows 10 box I'm running Plex.  The I edited the L2P.py file to reflect the IP and port of the server (I read after that "0.0.0.0" was a default, so it showing up on the cli after trying to start L2P was ok, but I didn't change back).  I changed the default listening port only because L2P wasn't working, so I wanted to make sure there wasn't a conflict.  Again, didn't change it back since it didn't look like it impacted anything.

Using the CLI, L2P looks like it is starting (http://10.100.200.190:6177/device.xml returns:
\<root>
\<specVersion>
\<major>1\</major>
\<minor>0\</minor>
\</specVersion>
\<device>
\<deviceType>urn:schemas-upnp-org:device:MediaServer:1\</deviceType>
\<friendlyName>Locast2Plex\</friendlyName>
\<manufacturer>Silicondust\</manufacturer>
\<modelName>HDHR3-US\</modelName>
\<modelNumber>HDHR3-US\</modelNumber>
\<serialNumber/>
\<UDN>uuid:\<don't know if this is something that identifies me, so removed it from cut-and-paste>\</UDN>
\</device>
\<URLBase>http://10.100.200.190:6177\</URLBase>
\</root>

Adding the virtual tuner to Plex *looks* like it's working (ie when I add it, it says it has found 37 channels, but once the rebuild of the guide is complete, when I exit the tuner config screen and return, it says "Device not found. Ensure your device is powered on and connected to your network".  Interestingly, I don't get a "Device Settings" option under the L2P tuner to make changes.  I have to delete that configuration and recreate it.

2 other things, just in case:
I am running an actual tuner as well (HDHomeRun Extend).  It mostly works (with the usual signal issues from using an OTA antenna).
I did not reboot after installing Python or L2P.  I bring this up because Python is not in the search path.  I had to specify the full path to python.exe on the cli when I started up the L2P script.

Thoughts?

**Comment by CTJohnK** [comment]
If you are referring to the Locast2Plex listing under Manage/Live TV & DVR, mine shows the same message but works fine to watch and record.

**Comment by diana1055** [comment]
Also make sure that the Python and Locast2Plex (and ffmpeg if using) directories are in the PATH,

**Comment by BH000** [comment]
> 
> 
> If you are referring to the Locast2Plex listing under Manage/Live TV & DVR, mine shows the same message but works fine to watch and record.

Yes, that's what I was referring to.  That's odd.  With my HDHomerun I can go in and tweak the channels.  With L2P, I have to delete the definition and recreate it if I want to add/drop/rescan channels.  That's kind of a major shortcoming.

I just re-added L2P.  I removed any channels that I get from my OTA (HD Homerun).  That only left 2 channels.  One showed up in the guide, the other did not.  The one that did show up still yielded the error, so I still have something incorrect.

**Comment by BH000** [comment]
> 
> 
> Also make sure that the Python and Locast2Plex (and ffmpeg if using) directories are in the PATH,

I added those paths and verified they are being picked up.  Unfortunately, no change.

It is my understanding that ffmpeg only gets installed if running on a Mac or Linux.  I don't have it installed (again, Windows 10).  Are any special rights needed in the windows FW for this to work?  I haven't looked in there yet.

**Comment by BH000** [comment]
When I try to watch the channel that should be coming via L2P, I see the following in the L2P CLI window on the server (I haven't moved it to a service yet since it isn't working):

Locast2Plex v0.4.2
DEBUG MODE ACTIVE
UUID found.
UUID set to: /<snipped>...
Logging into Locast using username /<snipped>...
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: /<snipped>
Getting user location...
User location obtained as /<snipped
Getting user's media market (DMA)...
DMA found as 506
Getting list of stations based on DMA...
Loading FCC Stations list...
Starting device server on 10.100.200.190:6177
Starting SSDP server...
10.100.200.190 - - [24/Aug/2020 18:29:09] "GET /lineup.json HTTP/1.0" 200 -
10.100.200.190 - - [24/Aug/2020 18:29:09] "GET /discover.json HTTP/1.0" 200 -
10.100.200.190 - - [24/Aug/2020 18:29:09] "GET /lineup_status.json HTTP/1.0" 200 -
Getting station info for 1571514244891...
Determining best video stream for 1571514244891...
Found 0 Playlists
No variant streams found for this station.  Assuming single stream only.
10.100.200.190 - - [24/Aug/2020 18:29:09] "GET /watch/1571514244891 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('10.100.200.190', 62375)
Traceback (most recent call last):
  File "c:\python27\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python27\lib\SocketServer.py", line 655, in __init__
    self.handle()
  File "c:\python27\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "c:\python27\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "main.py", line 91, in do_GET
    ffmpeg_proc = subprocess.Popen(["ffmpeg", "-i", channelUri, "-codec", "copy", "-f", "mpegts", "pipe:1"], stdout=subprocess.PIPE)
  File "c:\python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "c:\python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
----------------------------------------
Getting station info for 1571514244891...
Determining best video stream for 1571514244891...
Found 0 Playlists
No variant streams found for this station.  Assuming single stream only.
10.100.200.190 - - [24/Aug/2020 18:29:09] "GET /watch/1571514244891 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('10.100.200.190', 62378)
Traceback (most recent call last):
  File "c:\python27\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python27\lib\SocketServer.py", line 655, in __init__
    self.handle()
  File "c:\python27\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "c:\python27\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "main.py", line 91, in do_GET
    ffmpeg_proc = subprocess.Popen(["ffmpeg", "-i", channelUri, "-codec", "copy", "-f", "mpegts", "pipe:1"], stdout=subprocess.PIPE)
  File "c:\python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "c:\python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
----------------------------------------
Getting station info for 1571514244891...
Determining best video stream for 1571514244891...
Found 0 Playlists
No variant streams found for this station.  Assuming single stream only.
10.100.200.190 - - [24/Aug/2020 18:29:11] "GET /watch/1571514244891 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('10.100.200.190', 62385)
Traceback (most recent call last):
  File "c:\python27\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python27\lib\SocketServer.py", line 655, in __init__
    self.handle()
  File "c:\python27\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "c:\python27\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "main.py", line 91, in do_GET
    ffmpeg_proc = subprocess.Popen(["ffmpeg", "-i", channelUri, "-codec", "copy", "-f", "mpegts", "pipe:1"], stdout=subprocess.PIPE)
  File "c:\python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "c:\python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
----------------------------------------
Getting station info for 1571514244891...
10.100.200.190 - - [24/Aug/2020 18:29:14] "GET /discover.json HTTP/1.0" 200 -
10.100.200.190 - - [24/Aug/2020 18:29:14] "GET /lineup_status.json HTTP/1.0" 200 -
Determining best video stream for 1571514244891...
Found 0 Playlists
No variant streams found for this station.  Assuming single stream only.
10.100.200.190 - - [24/Aug/2020 18:29:14] "GET /watch/1571514244891 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('10.100.200.190', 62388)
Traceback (most recent call last):
  File "c:\python27\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python27\lib\SocketServer.py", line 655, in __init__
    self.handle()
  File "c:\python27\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "c:\python27\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "main.py", line 91, in do_GET
    ffmpeg_proc = subprocess.Popen(["ffmpeg", "-i", channelUri, "-codec", "copy", "-f", "mpegts", "pipe:1"], stdout=subprocess.PIPE)
  File "c:\python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "c:\python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
----------------------------------------
10.100.200.190 - - [24/Aug/2020 18:29:19] "GET /discover.json HTTP/1.0" 200 -
10.100.200.190 - - [24/Aug/2020 18:29:19] "GET /lineup_status.json HTTP/1.0" 200 -
Getting station info for 1571514244891...
Determining best video stream for 1571514244891...
Found 0 Playlists
No variant streams found for this station.  Assuming single stream only.
10.100.200.190 - - [24/Aug/2020 18:29:22] "GET /watch/1571514244891 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('10.100.200.190', 62410)
Traceback (most recent call last):
  File "c:\python27\lib\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "c:\python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python27\lib\SocketServer.py", line 655, in __init__
    self.handle()
  File "c:\python27\lib\BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "c:\python27\lib\BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "main.py", line 91, in do_GET
    ffmpeg_proc = subprocess.Popen(["ffmpeg", "-i", channelUri, "-codec", "copy", "-f", "mpegts", "pipe:1"], stdout=subprocess.PIPE)
  File "c:\python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "c:\python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
----------------------------------------


On the browser where I try to watch the channel I get:
Playback Error
Could not tune channel.  Please check your tuner or antenna.

This goes to a question I asked before, because I see a reference to ffmpeg in this log.  Is it required for Windows servers?  The docs implied it was only needed for Mac and Linux servers.

**Comment by tgorgdotcom** [comment]
Yeah, sorry about that.  FFmpeg is not included for Windows users.  I'm trying to fix that, but in the meantime, you can install ffmpeg separately and it should work (just make sure the ffmpeg install folder is in the PATH environment var)

**Comment by BH000** [comment]
> 
> 
> Yeah, sorry about that. FFmpeg is not included for Windows users. I'm trying to fix that, but in the meantime, you can install ffmpeg separately and it should work (just make sure the ffmpeg install folder is in the PATH environment var)

That did it.  So the wording of the install docs is a little ambiguous.  It sounds like you only need ffmpeg if you're running L2P on Linux or Mac.  Thank you.  This is going to be fun to play around with.

**Comment by tgorgdotcom** [comment]
Note: in newer versions ffmpeg is now included for Windows users.  Closing this issue now.
