### ISSUE TITLE
"Address already in use" error

### ISSUE THREAD

**Issue by craigarno** [tgorgdotcom/locast2plex#5]
```
Locast2Plex v0.3.0
DEBUG MODE ACTIVE
UUID found.
UUID set to: nlkmantz...
Logging into Locast using username me@mydomain.com...
Logon token is xxxxxxx
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 1595525521
Getting user location...
User location obtained as 47.7229/-122.1961
Getting user's media market (DMA)...
DMA found as 819
Getting list of stations based on DMA...
Loading FCC Stations list...
Starting device server on 0.0.0.0:6077
Starting SSDP server...
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 232, in ssdpServerProcess
    ssdp.run()
  File "/home/usr/craig/Project/locast2plex/SSDPServer.py", line 54, in run
    self.sock.bind(('0.0.0.0', SSDP_PORT))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
^C^C received, shutting down the server
```

> ~/Project/locast2plex% lsb_release -a                                                                              
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    **Ubuntu 16.04.6 LTS**
> Release:        16.04
> Codename:       xenial

> ~/Project/locast2plex% python --version                                                                            
> **Python 2.7.12**

> ~/Project/locast2plex% ffmpeg --version                                                                            
> ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers

I tried multiple addresses and ports.  Also looked at "lsof -i" and "netstat -tulp" and 6077 and the other ports I tried are available.

I'm not a Python programmer.  Any idea why the program isn't able to setup the "server"?

Or is someone willing to share a working Docker Container?

**Comment by tgorgdotcom** [comment]
Hello there.  I just realized I forgot to mention another port in the docs.  You'll need to check if port `1900` is in use as well.  This is to emulate telly/hdhomerun behavior to respond to SSDP discovery requests.  Sorry for the miscommunication.  I'll update the readme accordingly.

Hope that helps!

**Comment by craigarno** [comment]
Information about port 1900 got me past this hurdle.

It turns out Emby runs on port 1900.  Stopped the Emby server and

> Locast2Plex v0.3.0
> DEBUG MODE ACTIVE
> UUID found.
> UUID set to: nlkmknntz...
> Logging into Locast using username craig@myDomain.org...
> Logon token is eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjcmFpZ0Bhcm5vLmNvbSSIsInJvbGUiOjEsImV4cCI6MTYyMTk5OTE2Nn0.YNRRrjLXi_L9SXjdCGXlTNk5i2tu66TvhQqTiOTSIzI
> Validating User Info...
> User Info obtained.
> User didDonate: True
> User donationExpire: 1595525521
> Getting user location...
> User location obtained as 47.7229/-122.1961
> Getting user's media market (DMA)...
> DMA found as 819
> Getting list of stations based on DMA...
> Loading FCC Stations list...
> Starting device server on 0.0.0.0:6077
> Starting SSDP server...

And now it's up, but not running.  For whatever reason I can't play any of the shows I now see in the TV Guide.

But success so far as, all channels appear, I'm able to map these channels after a little fiddling with Plex Guide Zip code.  The TV Guide in Plex looks right.  Very promising!

So lets close this one as solved, and I'll open another for the next one.
