### ISSUE TITLE
Error during login: [Errno -3] Try again

### ISSUE THREAD

**Issue by Shadowmind33** [tgorgdotcom/locast2plex#51]
I'm trying to run this on Synology Docker, when it attempts to run it stops with the following;

Locast2Plex v0.4.2
DEBUG MODE ACTIVE
UUID found.
UUID set to: hmwhuwux...
Logging into Locast using username [my locast username]
Error during login: [Errno -3] Try again
Exiting...

I've run this on my PC running Docker as well and no problems there, I'm just curious if I missed something.

**Comment by diana1055** [comment]
Try logging into Locast directly? I saw a similar message when a shut down Locast2plex while recording 4 streams.  It wouldn’t allow a login because I had 4 streams running and it took over an hour for them to time out.

**Comment by Shadowmind33** [comment]
Ok I resolved it.  I needed to recreate the container, only this time I would go into the advanced settings to the network tab and check the box for "Use the same network as Docker Host" because this isn't available to modify in the Docker interface after the container is created.  Basically it wasn't getting an internet connection.
