### ISSUE TITLE
NoneType and int error

### ISSUE THREAD

**Issue by deathbybandaid** [tgorgdotcom/locast2plex#53]
Found just while doing a test run, with a fresh locast account without donating

````
locast@locast2plex:/home/locast2plex# python main.py -u:REDACTED -p:REDACTED --debug --addy:0.0.0.0
Locast2Plex v0.4.2
DEBUG MODE ACTIVE
UUID found.
UUID set to: REDACTED...
Logging into Locast using username REDACTED...
Validating User Info...
User Info obtained.
User didDonate: False
Traceback (most recent call last):
  File "main.py", line 331, in <module>
    if (not locast.login(CONFIG_LOCAST_USERNAME, CONFIG_LOCAST_PASSWORD)) or (not locast.validate_user()):
  File "/home/locast2plex/LocastService.py", line 85, in validate_user
    print("User donationExpire: " + str(userRes['donationExpire'] / 1000))
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
````

**Comment by diana1055** [comment]
It doesn’t work with an unpaid Locast acct - you don’t get the stream url if you don’t donate.  You get the ‘Please donate’ stream first.  Since you had no userID or password, there were null values passed to the code which caused the crash.  Read the install documentation.

**Comment by deathbybandaid** [comment]
I knew it wouldn't work without paying.

This is simply a bug report.

it looks like `if not userRes['didDonate']:` is not catching properly, and "False" is coming through as a string, and not a boolean.

**Comment by deathbybandaid** [comment]
Closing as the issue doesn't happen since newer releases
