### ISSUE TITLE
Locast2Plex works with Jellyfin

### ISSUE THREAD

**Issue by seantdavidson** [tgorgdotcom/locast2plex#55]
Just wanted to leave a note that this will also work with Jellyfin. You can't autodiscover when you setup DVR but you can manually enter the IP and port and works great. You will need to setup way to import the guide, since I use Docker I was able to spin up a docker with xml guide to import.

**Comment by tgorgdotcom** [comment]
Nice.  I updated the Readme at the top.  Maybe sooner or later we will have to change the name...
