### ISSUE TITLE
Can't Tune in Plex

### ISSUE THREAD

**Issue by wdreiling** [tgorgdotcom/locast2plex#57]
I can find the device in plex and I can add it.  When I scan channels I see everything I expect (odd though there is no signal strength like for my standard HDHomeRun).  After completing setup I am unable to tune any channels.  I have attached my log.  
[Locast2Plex Error Log.txt](https://github.com/tgorgdotcom/locast2plex/files/5139936/Locast2Plex.Error.Log.txt)

**Comment by FozzieBear** [comment]
It appears you're missing ffmpeg, or it's not on the Path where it can be found. Make sure to download ffmpeg (https://ffmpeg.org/download.html) and ensure it's in your system's PATH, or drop the exe in the same folder you're running the script from.

**Comment by wdreiling** [comment]
My Hero!  I found an ffmpeg install guide and got it all buttoned up and was able to stream!  Thanks for being there!
