### ISSUE TITLE
Support for ARM64/Raspberry Pi support

### ISSUE THREAD

**Issue by cotysmith** [tgorgdotcom/locast2plex#58]
Running Docker on RPi4 with OMV/debian. After using docker-compose and starting the container, the log continues to display standard_init_linux.go:211: exec user process caused "exec format error"

Is this due to architecture support? I have both ffmpeg and python 2.7.13 installed locally as well.

**Comment by tgorgdotcom** [comment]
Hmmm, I don't think there should be any issues with architecture with running the script.  Is the log displaying the error first thing, or after a few messages?  If you can post the log contents, that would be super helpful.  Thanks!

**Comment by cotysmith** [comment]
Yes, this is the first error in the log and continues to repeat every few seconds

> standard_init_linux.go:211: exec user process caused "exec format error",
> standard_init_linux.go:211: exec user process caused "exec format error",
> standard_init_linux.go:211: exec user process caused "exec format error",

It seems odd that it's continuing to restart and doesn't ever seem to get started as a service. I've also attached the contents of my flat inspect log

> {
>     "AppArmorProfile": "",
>     "Args": [
>         "/app/main.py",
>         "2>&1"
>     ],
>     "Config": {
>         "AttachStderr": false,
>         "AttachStdin": false,
>         "AttachStdout": false,
>         "Cmd": null,
>         "Domainname": "",
>         "Entrypoint": [
>             "python",
>             "/app/main.py",
>             "2>&1"
>         ],
>         "Env": [
>             "username=user",
>             "password=pass",
>             "external_addy=192.168.99.77",
>             "external_port=6077",
>             "debug=yes",
>             "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
>             "LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64"
>         ],
>         "ExposedPorts": {
>             "1900/udp": {},
>             "6077/tcp": {}
>         },
>         "Hostname": "x",
>         "Image": "tgorg/locast2plex",
>         "Labels": {
>             "com.docker.compose.config-hash": "b75eb4f8ecb69a4d9160b086f346d6de94a43926",
>             "com.docker.compose.container-number": "1",
>             "com.docker.compose.oneoff": "False",
>             "com.docker.compose.project": "locast2plex",
>             "com.docker.compose.service": "locast2plex",
>             "com.docker.compose.version": "1.5.0",
>             "maintainer": "Thomas Gorgolione <thomas@tgorg.com>"
>         },
>         "OnBuild": null,
>         "OpenStdin": false,
>         "StdinOnce": false,
>         "Tty": false,
>         "User": "",
>         "Volumes": null,
>         "WorkingDir": ""
>     },
>     "Created": "2020-08-29T11:57:50.114647299Z",
>     "Driver": "overlay2",
>     "ExecIDs": null,
>     "GraphDriver": {
>         "Data": {
>             "LowerDir": "/var/lib/docker/overlay2/245e6423e3556d851654a645adc488e9002632f8e589ab8279db7a1e28007c24-init/diff:/var/lib/docker/overlay2/fccd067014cc9089de3544295a1aab7aa066cf6b7e3646f229bb282b20f41934/diff:/var/lib/docker/overlay2/aa9057233f93c7e4bf5664aca501cefee9f1ffdff389a7909d54d0ccd73f7e36/diff:/var/lib/docker/overlay2/c5cceb69911201d1c4222eb7bd7397f49eeeda62767e1c22ac4bf561040ec4dc/diff:/var/lib/docker/overlay2/fbc5259e28968da58b5c7ea4a16eb6addb199baba05bb1f918a6d65d41c6a180/diff:/var/lib/docker/overlay2/2b5f8a3783602fd8abbc82b14b55db8bd2c22b16b501e9bed0aad940a3c96a94/diff:/var/lib/docker/overlay2/150e02e26e5adb29c593963913a13ee061a9be30e3554df09d3f57961ad4754f/diff:/var/lib/docker/overlay2/dc79ca64efc085a528b9ac431a497ba4315d02f12036f9772c6912c308bfcae3/diff:/var/lib/docker/overlay2/716094b438b0b84539e5a182365e5d138151011a9d2bd48c0ebee4f2827a0d65/diff:/var/lib/docker/overlay2/bf95d321736fb11d9be6a122792c35a901fba4e2b527ca4be9fa2a4eb732415f/diff:/var/lib/docker/overlay2/06964901f2ee2fd54dd27a8509d212ce633d6a225c67bc934b7862b1e38142fb/diff:/var/lib/docker/overlay2/079663a18408f8881944bdffe63b0d90c6ca6a4a3597e67a82c5c3d1e979d348/diff:/var/lib/docker/overlay2/fb7e9426bb5fb95d2a947b58e7e76c51a44d37a0d281e1ff8413b988281a8c7a/diff:/var/lib/docker/overlay2/c0273072c2f8a1866bba0b41c72244cfddbebb7e7f3c83af467f3f2f2604756b/diff",
>             "MergedDir": "/var/lib/docker/overlay2/245e6423e3556d851654a645adc488e9002632f8e589ab8279db7a1e28007c24/merged",
>             "UpperDir": "/var/lib/docker/overlay2/245e6423e3556d851654a645adc488e9002632f8e589ab8279db7a1e28007c24/diff",
>             "WorkDir": "/var/lib/docker/overlay2/245e6423e3556d851654a645adc488e9002632f8e589ab8279db7a1e28007c24/work"
>         },
>         "Name": "overlay2"
>     },
>     "HostConfig": {
>         "AutoRemove": false,
>         "Binds": [],
>         "BlkioDeviceReadBps": null,
>         "BlkioDeviceReadIOps": null,
>         "BlkioDeviceWriteBps": null,
>         "BlkioDeviceWriteIOps": null,
>         "BlkioWeight": 0,
>         "BlkioWeightDevice": null,
>         "CapAdd": null,
>         "CapDrop": null,
>         "Capabilities": null,
>         "Cgroup": "",
>         "CgroupParent": "",
>         "ConsoleSize": [
>             0,
>             0
>         ],
>         "ContainerIDFile": "",
>         "CpuCount": 0,
>         "CpuPercent": 0,
>         "CpuPeriod": 0,
>         "CpuQuota": 0,
>         "CpuRealtimePeriod": 0,
>         "CpuRealtimeRuntime": 0,
>         "CpuShares": 0,
>         "CpusetCpus": "",
>         "CpusetMems": "",
>         "DeviceCgroupRules": null,
>         "DeviceRequests": null,
>         "Devices": [],
>         "Dns": null,
>         "DnsOptions": null,
>         "DnsSearch": null,
>         "ExtraHosts": null,
>         "GroupAdd": null,
>         "IOMaximumBandwidth": 0,
>         "IOMaximumIOps": 0,
>         "IpcMode": "shareable",
>         "Isolation": "",
>         "KernelMemory": 0,
>         "KernelMemoryTCP": 0,
>         "Links": null,
>         "LogConfig": {
>             "Config": {},
>             "Type": "json-file"
>         },
>         "MaskedPaths": [
>             "/proc/asound",
>             "/proc/acpi",
>             "/proc/kcore",
>             "/proc/keys",
>             "/proc/latency_stats",
>             "/proc/timer_list",
>             "/proc/timer_stats",
>             "/proc/sched_debug",
>             "/proc/scsi",
>             "/sys/firmware"
>         ],
>         "Memory": 0,
>         "MemoryReservation": 0,
>         "MemorySwap": 0,
>         "MemorySwappiness": null,
>         "NanoCpus": 0,
>         "NetworkMode": "locast2plex_default",
>         "OomKillDisable": null,
>         "OomScoreAdj": 0,
>         "PidMode": "",
>         "PidsLimit": null,
>         "PortBindings": {
>             "1900/udp": [
>                 {
>                     "HostIp": "",
>                     "HostPort": "1900"
>                 }
>             ],
>             "6077/tcp": [
>                 {
>                     "HostIp": "",
>                     "HostPort": "6077"
>                 }
>             ]
>         },
>         "Privileged": false,
>         "PublishAllPorts": false,
>         "ReadonlyPaths": [
>             "/proc/bus",
>             "/proc/fs",
>             "/proc/irq",
>             "/proc/sys",
>             "/proc/sysrq-trigger"
>         ],
>         "ReadonlyRootfs": false,
>         "RestartPolicy": {
>             "MaximumRetryCount": 0,
>             "Name": "unless-stopped"
>         },
>         "Runtime": "runc",
>         "SecurityOpt": null,
>         "ShmSize": 67108864,
>         "UTSMode": "",
>         "Ulimits": [],
>         "UsernsMode": "",
>         "VolumeDriver": "",
>         "VolumesFrom": null
>     },
>     "HostnamePath": "/var/lib/docker/containers/937fe6b557eb578e4487a508b99be62685325572300d48d756aa8c6b98955a77/hostname",
>     "HostsPath": "/var/lib/docker/containers/937fe6b557eb578e4487a508b99be62685325572300d48d756aa8c6b98955a77/hosts",
>     "Id": "937fe6b557eb578e4487a508b99be62685325572300d48d756aa8c6b98955a77",
>     "Image": "sha256:04a4449340e72b282c55bdb3204bbcba6139113450fc86234d4841abab131499",
>     "LogPath": "/var/lib/docker/containers/937fe6b557eb578e4487a508b99be62685325572300d48d756aa8c6b98955a77/937fe6b557eb578e4487a508b99be62685325572300d48d756aa8c6b98955a77-json.log",
>     "MountLabel": "",
>     "Mounts": [],
>     "Name": "/locast2plex",
>     "NetworkSettings": {
>         "Bridge": "",
>         "EndpointID": "",
>         "Gateway": "",
>         "GlobalIPv6Address": "",
>         "GlobalIPv6PrefixLen": 0,
>         "HairpinMode": false,
>         "IPAddress": "",
>         "IPPrefixLen": 0,
>         "IPv6Gateway": "",
>         "LinkLocalIPv6Address": "",
>         "LinkLocalIPv6PrefixLen": 0,
>         "MacAddress": "",
>         "Networks": {
>             "locast2plex_default": {
>                 "Aliases": [
>                     "locast2plex",
>                     "x"
>                 ],
>                 "DriverOpts": null,
>                 "EndpointID": "",
>                 "Gateway": "",
>                 "GlobalIPv6Address": "",
>                 "GlobalIPv6PrefixLen": 0,
>                 "IPAMConfig": {},
>                 "IPAddress": "",
>                 "IPPrefixLen": 0,
>                 "IPv6Gateway": "",
>                 "Links": [],
>                 "MacAddress": "",
>                 "NetworkID": "x"
>             }
>         },
>         "Ports": {},
>         "SandboxID": "x",
>         "SandboxKey": "/var/run/docker/netns/x",
>         "SecondaryIPAddresses": null,
>         "SecondaryIPv6Addresses": null
>     },
>     "Path": "python",
>     "Platform": "linux",
>     "Portainer": {
>         "ResourceControl": {
>             "Id": 18,
>             "ResourceId": "locast2plex",
>             "SubResourceIds": [],
>             "Type": 6,
>             "UserAccesses": [],
>             "TeamAccesses": [],
>             "Public": false,
>             "AdministratorsOnly": true,
>             "System": false
>         }
>     },
>     "ProcessLabel": "",
>     "ResolvConfPath": "/var/lib/docker/containers/937fe6b557eb578e4487a508b99be62685325572300d48d756aa8c6b98955a77/resolv.conf",
>     "RestartCount": 7,
>     "State": {
>         "Dead": false,
>         "Error": "",
>         "ExitCode": 1,
>         "FinishedAt": "2020-08-29T12:00:46.548696085Z",
>         "OOMKilled": false,
>         "Paused": false,
>         "Pid": 0,
>         "Restarting": true,
>         "Running": true,
>         "StartedAt": "2020-08-29T12:00:46.375664788Z",
>         "Status": "restarting"
>     }
> }

Built using these docker-compose settings

> version: '2'
> 
> services:
>   locast2plex:
>     image: tgorg/locast2plex
>     container_name: locast2plex
>     ports:
>       - "6077:6077"
>       - "1900:1900/udp"
>     restart: unless-stopped
>     environment:
>       - username=user
>       - 'password=pass'
>       - external_addy=192.168.99.77
>       - external_port=6077
>       - debug=yes

**Comment by tgorgdotcom** [comment]
Oh, I think I must have been half asleep when I responded earlier.  I think there would definitely be issues running from Docker as the image format is for x86.  Running the script outside of Docker should work though.  I'll have to do some research on multi-arch Docker images.

**Comment by cotysmith** [comment]
Thanks for helping me pin this one down, it had been wrecking my head.
