### ISSUE TITLE
No streams found for this station.  Skipping...

### ISSUE THREAD

**Issue by craigarno** [tgorgdotcom/locast2plex#6]
![image](https://user-images.githubusercontent.com/4262930/82979976-32d93900-9f9d-11ea-9fbf-5a3972d475dc.png)

```
Locast2Plex v0.3.0
DEBUG MODE ACTIVE
UUID found.
UUID set to: nlkmknntz...
Logging into Locast using username craig@myDomain.org...
Logon token is xxxxxxx
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 1595525521
Getting user location...
Getting list of stations based on DMA...
Loading FCC Stations list...
Starting device server on 0.0.0.0:6077
Starting SSDP server...


127.0.0.1 - - [26/May/2020 22:02:26] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [26/May/2020 22:02:26] "GET /lineup.json HTTP/1.0" 200 -
127.0.0.1 - - [26/May/2020 22:02:26] "GET /lineup_status.json HTTP/1.0" 200 -
Getting station info for 1572389490915...
Determining best video stream for 1572389490915...
Found 0 Playlists
No streams found for this station.  Skipping...
127.0.0.1 - - [26/May/2020 22:02:26] "GET /watch/1572389490915 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41614)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "main.py", line 91, in do_GET
    ffmpeg_proc = subprocess.Popen(["ffmpeg", "-i", channelUri, "-codec", "copy", "-f", "mpegts", "pipe:1"], stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
----------------------------------------
Getting station info for 1572389490915...
Determining best video stream for 1572389490915...
Found 0 Playlists
No streams found for this station.  Skipping...
127.0.0.1 - - [26/May/2020 22:02:27] "GET /watch/1572389490915 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41620)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "main.py", line 91, in do_GET
    ffmpeg_proc = subprocess.Popen(["ffmpeg", "-i", channelUri, "-codec", "copy", "-f", "mpegts", "pipe:1"], stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
----------------------------------------
Getting station info for 1572389490915...
Determining best video stream for 1572389490915...
Found 0 Playlists
No streams found for this station.  Skipping...
127.0.0.1 - - [26/May/2020 22:02:28] "GET /watch/1572389490915 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41626)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
```

Keeps repeating this error.

**Comment by craigarno** [comment]
**Some success**; Interesting that Channel 4.1 does find and play.  Here is a short clip start to finish.  My hardware isn't fast enough to play realtime, so I ended the program at the end where you see all the exception processing.

```
DMA found as 819
Getting list of stations based on DMA...
Loading FCC Stations list...
Starting device server on 0.0.0.0:6077
Starting SSDP server...
127.0.0.1 - - [26/May/2020 22:40:57] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [26/May/2020 22:40:57] "GET /lineup.json HTTP/1.0" 200 -
127.0.0.1 - - [26/May/2020 22:40:57] "GET /lineup_status.json HTTP/1.0" 200 -
Getting station info for 1572389490750...
Determining best video stream for 1572389490750...
Found 3 Playlists
1572389490750 will use 1280x720 resolution at 2700000bps
127.0.0.1 - - [26/May/2020 22:40:58] "GET /watch/1572389490750 HTTP/1.1" 200 -
ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv --enable-version3 --disable-doc --disable-programs --disable-avdevice --disable-avfilter --disable-avformat --disable-avresample --disable-postproc --disable-swscale --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libvo_aacenc --enable-libvo_amrwbenc
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[https @ 0xa1f2a0] No trailing CRLF found in HTTP header.
Input #0, hls,applehttp, from 'https://acdn.locastnet.org/variant/4DSsXJAzni9BUppsh0zteoZPDYvabtGpRzJtKf5cayhKFCJWG7OZ8UbuoE9HsrlZ24PVuIy7EyHHDnaaOtQMpgybcM9zE5jthrVseFKB79aX.m3u8':
  Duration: N/A, start: 7654.718933, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], Closed Captions, 30 fps, 30 tbr, 90k tbn, 60 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 181 kb/s
Output #0, mpegts, to 'pipe:1':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 30 fps, 30 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo, 181 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[https @ 0xe178c0] No trailing CRLF found in HTTP header.
[https @ 0x134a680] No trailing CRLF found in HTTP header.
127.0.0.1 - - [26/May/2020 22:41:00] "GET /discover.json HTTP/1.0" 200 -.4kbits/s    
127.0.0.1 - - [26/May/2020 22:41:00] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [26/May/2020 22:41:03] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [26/May/2020 22:41:03] "GET /lineup_status.json HTTP/1.0" 200 -
[https @ 0x1353620] No trailing CRLF found in HTTP header.
127.0.0.1 - - [26/May/2020 22:41:06] "GET /discover.json HTTP/1.0" 200 -.7kbits/s    
127.0.0.1 - - [26/May/2020 22:41:06] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [26/May/2020 22:41:09] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [26/May/2020 22:41:09] "GET /lineup_status.json HTTP/1.0" 200 -
[https @ 0x124c3e0] No trailing CRLF found in HTTP header.
127.0.0.1 - - [26/May/2020 22:41:12] "GET /discover.json HTTP/1.0" 200 -.4kbits/s    
127.0.0.1 - - [26/May/2020 22:41:12] "GET /lineup_status.json HTTP/1.0" 200 -
127.0.0.1 - - [26/May/2020 22:41:13] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [26/May/2020 22:41:13] "GET /lineup_status.json HTTP/1.0" 200 -
[https @ 0x124c3e0] No trailing CRLF found in HTTP header.
----------------------------------------kB time=00:00:30.01 bitrate=1215.2kbits/s    
Exception happened during processing of request from ('127.0.0.1', 43856)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
frame=  981 fps= 53 q=-1.0 Lsize=    5022kB time=00:00:32.68 bitrate=1258.7kbits/s    
video:3754kB audio:766kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 11.082366%
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
Exiting normally, received signal 15.
```

**Comment by craigarno** [comment]
Also channels 5.1, 7.1 work.  Seems sub-channels have trouble.  I'm proceeding to try to get to where I can record the SpaceX launch tomorrow.  Hopefully in 1080p.

**Comment by craigarno** [comment]
I was able to record several news casts overnight, so looks like it's generally working, just the specifics on sub-channels like 4.2, 4.3, 5.2, 5.3, 7.2, 7.3, 7.4, etc.  I don't know where to look to fix this.

**Comment by tgorgdotcom** [comment]
Ah,  I think I might know what the problem with the subchannels are.  For some stations, locast provides multiple bandwidth streams, but I think these subchannels only provide one stream.  It's choking on the logic I have to pick the best multi bandwidth stream.  I'll look into it, but unfortunately can't promise any updates today.

**Comment by craigarno** [comment]
No problem, I can get SpaceX recorded from primary channels.  The rest is more long term optimizing to get it all working right as a bridge between Locast and Plex.  I'm thrilled to have the success we have so far with 0.3 software.  I now have capability I didn't have yesterday with Plex.

**Comment by craigarno** [comment]
I noticed one more interesting thing  When I select "HD Channels only" in the guide, then all the channels which don't work go away.  Of course all 46 channels work in Locast.  Here is the HD filtered display (the channels which work):
![image](https://user-images.githubusercontent.com/4262930/83321566-68805b00-a205-11ea-9f1c-7dad426d1f69.png)

**Comment by tgorgdotcom** [comment]
Yup, those "single-stream" channels are usually standard definition.  I have a fix coming soon -- I found a few other bugs with regards to channel detection that I'm working on as well.

**Comment by craigarno** [comment]
I'm still trying to figure things out, like it appears Locast only provides 720p-stereo, even for stations broadcasting 1080p-5.1, unless Plex is modifying content.  Not a huge deal, I can see how Locast  might do this to contain bandwidth requirements for their operation.  It would still be nice if Locast (and/or Plex) were to provide channel content as-is, without modification except for advertising removal.  Maybe later when Locast gets more established and money is used to improve performance instead of promoting quickest market growth.

SD channels I'd mostly want for convenience and content.  Nice to have.

I looked at your code, it looks like you use ffmpeg just to copy (not transcode) Locast content for the Plex system.  I wonder if it's Plex which is transcoding to lower resolution while placing the result in TS containers?

I look forward to any improvements you can accomplish.

I live behind a hill, so using an antenna doesn't accomplish anything for TV reception.

**Comment by tgorgdotcom** [comment]
Just updated the codebase to 0.4.0.  This should fix issues with tuning to the channels you've been having trouble with.  Also should autodetect more channels.  Let me know if that works.

**Comment by craigarno** [comment]
By the time I did a pull, you were already up to 0.4.1.  I'm not very
good with GIT yet, but I'm getting there :-[

It works as near as I can tell on all channels that Plex can see.  I see
a few disturbing things on the console, but these don't appear to
prevent your script from working.  Does it matter that I'm using Linux
where lines end with only <LF>, and not Windows style <CR><LF>?  Or
Macintosh <CR>?  Or is there a specification which says lines must end
in <CR><LF>?

Good news is, it works!


Getting station info for 1572389490750...
Determining best video stream for 1572389490750...
Found 3 Playlists
1572389490750 will use 1280x720 resolution at 2700000bps
127.0.0.1 - - [08/Jun/2020 17:17:19] "GET /watch/1572389490750 HTTP/1.1"
200 -
ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the
FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1
--build-suffix=-ffmpeg --toolchain=hardened
--libdir=/usr/lib/x86_64-linux-gnu
--incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl
--enable-shared --disable-stripping --disable-decoder=libopenjpeg
--disable-decoder=libschroedinger --enable-avresample --enable-avisynth
--enable-gnutls --enable-ladspa --enable-libass --enable-libbluray
--enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite
--enable-libfontconfig --enable-libfreetype --enable-libfribidi
--enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame
--enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp
--enable-libschroedinger --enable-libshine --enable-libsnappy
--enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora
--enable-libtwolame --enable-libvorbis --enable-libvpx
--enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid
--enable-libzvbi --enable-openal --enable-opengl --enable-x11grab
--enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r
--enable-libx264 --enable-libopencv
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr
--extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg
--toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu
--incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl
--enable-shared --disable-stripping --disable-decoder=libopenjpeg
--disable-decoder=libschroedinger --enable-avresample --enable-avisynth
--enable-gnutls --enable-ladspa --enable-libass --enable-libbluray
--enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite
--enable-libfontconfig --enable-libfreetype --enable-libfribidi
--enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame
--enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp
--enable-libschroedinger --enable-libshine --enable-libsnappy
--enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora
--enable-libtwolame --enable-libvorbis --enable-libvpx
--enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid
--enable-libzvbi --enable-openal --enable-opengl --enable-x11grab
--enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r
--enable-libx264 --enable-libopencv --enable-version3 --disable-doc
--disable-programs --disable-avdevice --disable-avfilter
--disable-avformat --disable-avresample --disable-postproc
--disable-swscale --enable-libopencore_amrnb --enable-libopencore_amrwb
--enable-libvo_aacenc --enable-libvo_amrwbenc
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[https @ 0x22f7840] No trailing CRLF found in HTTP header.
Input #0, hls,applehttp, from
'https://acdn.locastnet.org/variant/1PfeB9mR6qS1r42q3sPi7DFdi4gizJZl6Ds87iZKjusV3rPT2ukwK46uwF3zvHSvTFsXU6IMxZepGsAjOil8kGhwuhroPtSKvg5QYQyl3GXs.m3u8':
  Duration: N/A, start: 61557.824356, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p,
1280x720 [SAR 1:1 DAR 16:9], Closed Captions, 30 fps, 30 tbr, 90k tbn,
60 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz,
stereo, fltp, 192 kb/s
Output #0, mpegts, to 'pipe:1':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 ([27][0][0][0] / 0x001B), yuv420p, 1280x720
[SAR 1:1 DAR 16:9], q=2-31, 30 fps, 30 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([15][0][0][0] / 0x000F), 48000 Hz, stereo,
192 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  113 fps=0.0 q=-1.0 size=    2260kB time=00:00:03.73
bitrate=4959.2kbits/[https @ 0x2a2fd80] No trailing CRLF found in HTTP
header.
frame=  196 fps=196 q=-1.0 size=    3931kB time=00:00:06.50
bitrate=4948.9kbits/frame=  272 fps=181 q=-1.0 size=    5449kB
time=00:00:09.03 bitrate=4942.8kbits/127.0.0.1 - - [08/Jun/2020
17:17:21] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:17:21] "GET /lineup_status.json HTTP/1.0"
200 -
[https @ 0x2a37440] No trailing CRLF found in HTTP header.
frame=  360 fps=177 q=-1.0 size=    7042kB time=00:00:12.01
bitrate=4802.8kbits/127.0.0.1 - - [08/Jun/2020 17:17:24] "GET
/discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:17:24] "GET /lineup_status.json HTTP/1.0"
200 -
[https @ 0x2a37440] No trailing CRLF found in HTTP header.
frame=  540 fps= 89 q=-1.0 size=    7673kB time=00:00:18.00
bitrate=3491.0kbits/127.0.0.1 - - [08/Jun/2020 17:17:27] "GET
/discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:17:27] "GET /lineup_status.json HTTP/1.0"
200 -
127.0.0.1 - - [08/Jun/2020 17:17:30] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:17:30] "GET /lineup_status.json HTTP/1.0"
200 -
[https @ 0x2a37440] No trailing CRLF found in HTTP header.
frame=  720 fps= 59 q=-1.0 size=    8307kB time=00:00:24.00
bitrate=2835.4kbits/127.0.0.1 - - [08/Jun/2020 17:17:33] "GET
/discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:17:33] "GET /lineup_status.json HTTP/1.0"
200 -
127.0.0.1 - - [08/Jun/2020 17:17:36] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:17:36] "GET /lineup_status.json HTTP/1.0"
200 -
[https @ 0x22f4780] No trailing CRLF found in HTTP header.
frame=  900 fps= 49 q=-1.0 size=    8942kB time=00:00:30.01
bitrate=2440.4kbits/127.0.0.1 - - [08/Jun/2020 17:17:39] "GET
/discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:17:39] "GET /lineup_status.json HTTP/1.0"
200 -
127.0.0.1 - - [08/Jun/2020 17:17:42] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:17:42] "GET /lineup_status.json HTTP/1.0"
200 -
[https @ 0x22f4780] No trailing CRLF found in HTTP header.
frame= 1080 fps= 44 q=-1.0 size=   10157kB time=00:00:36.01
bitrate=2310.6kbits/frame= 1256 fps= 50 q=-1.0 size=   11745kB
time=00:00:41.83 bitrate=2299.9kbits/127.0.0.1 - - [08/Jun/2020
17:17:45] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:17:45] "GET /lineup_status.json HTTP/1.0"
200 -
127.0.0.1 - - [08/Jun/2020 17:17:48] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:17:48] "GET /lineup_status.json HTTP/1.0"
200 -
[https @ 0x22f4780] No trailing CRLF found in HTTP header.
frame= 1260 fps= 41 q=-1.0 size=   11830kB time=00:00:42.00
bitrate=2307.1kbits/frame= 1349 fps= 43 q=-1.0 size=   13550kB
time=00:00:44.94 bitrate=2469.5kbits/127.0.0.1 - - [08/Jun/2020
17:17:51] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:17:51] "GET /lineup_status.json HTTP/1.0"
200 -
frame= 1438 fps= 45 q=-1.0 size=   15059kB time=00:00:47.91
bitrate=2574.6kbits/127.0.0.1 - - [08/Jun/2020 17:17:54] "GET
/discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:17:54] "GET /lineup_status.json HTTP/1.0"
200 -
[https @ 0x2658ec0] No trailing CRLF found in HTTP header.
frame= 1440 fps= 39 q=-1.0 size=   15073kB time=00:00:48.00
bitrate=2572.5kbits/127.0.0.1 - - [08/Jun/2020 17:17:57] "GET
/discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:17:57] "GET /lineup_status.json HTTP/1.0"
200 -
127.0.0.1 - - [08/Jun/2020 17:18:00] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:18:00] "GET /lineup_status.json HTTP/1.0"
200 -
[https @ 0x2a37440] No trailing CRLF found in HTTP header.
frame= 1620 fps= 37 q=-1.0 size=   16597kB time=00:00:54.01
bitrate=2517.1kbits/127.0.0.1 - - [08/Jun/2020 17:18:03] "GET
/discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:18:03] "GET /lineup_status.json HTTP/1.0"
200 -
frame= 1782 fps= 41 q=-1.0 size=   18076kB time=00:00:59.39
bitrate=2493.3kbits/127.0.0.1 - - [08/Jun/2020 17:18:06] "GET
/discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:18:06] "GET /lineup_status.json HTTP/1.0"
200 -
[https @ 0x2a37440] No trailing CRLF found in HTTP header.
frame= 1800 fps= 36 q=-1.0 size=   18262kB time=00:01:00.01
bitrate=2492.9kbits/127.0.0.1 - - [08/Jun/2020 17:18:09] "GET
/discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:18:09] "GET /lineup_status.json HTTP/1.0"
200 -
127.0.0.1 - - [08/Jun/2020 17:18:12] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:18:12] "GET /lineup_status.json HTTP/1.0"
200 -
[https @ 0x2a37440] No trailing CRLF found in HTTP header.
127.0.0.1 - - [08/Jun/2020 17:18:15] "GET /discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:18:15] "GET /lineup_status.json HTTP/1.0"
200 -
frame= 1980 fps= 35 q=-1.0 size=   18993kB time=00:01:06.00
bitrate=2357.2kbits/127.0.0.1 - - [08/Jun/2020 17:18:18] "GET
/discover.json HTTP/1.0" 200 -
127.0.0.1 - - [08/Jun/2020 17:18:18] "GET /lineup_status.json HTTP/1.0"
200 -
127.0.0.1 - - [08/Jun/2020 17:18:21] "GET /discover.json HTTP/1.0" 200 -
...

**Comment by tgorgdotcom** [comment]
Not sure where the line ending errors are coming from, but I'm glad it's working for you so far.  I'll close this one out, but if you start seeing errors that affect video watching, feel free to send another issue.
