### ISSUE TITLE
Wont load

### ISSUE THREAD

**Issue by zerolimit30** [tgorgdotcom/locast2plex#61]
Had this working perfect! This morning had a update i said to myself awesome update to make it better! updated and reboot now it wont load :( 

-------------------------------------------------------------
Locast2Plex v0.5.2
Traceback (most recent call last):
File "/app/main.py", line 331, in <module>
Tuner count set to 3
No UUID found. Generating one now...
config_handler.set('main', 'uuid', DEVICE_UUID)
File "/usr/lib/python2.7/ConfigParser.py", line 396, in set
raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'main'
-------------------------------------------------------------

**Comment by glockpete** [comment]
Exactly the same issue here with Unraid 3.8.6.

**Comment by goldengit** [comment]
+1 was working great for a month since I added the docker container - updated to latest and now getting same error as above ( running as docker container on Linux Ubuntu 20.04lts server.

**Comment by tri-ler** [comment]
In version 0.5 some of the old parameters were changed to use config.ini

**Comment by zerolimit30** [comment]
> In version 0.5 some of the old parameters were changed to use config.ini. The installation guide is updated to show this.

do you know how we can fix it on docker or what we need to change to get this to work again?

**Comment by tri-ler** [comment]
Create a config.ini file and mount it into the container as "/app/config.ini" and use the config_example.ini template to fill out the file. This fixed it for me.

**Comment by dcd** [comment]
that effectively breaks kubernetes, configmap/secret mount is ro and volume mounts cant use file paths at least for nfs... can we move config.ini outside of /app please?

**Comment by jamesmalachyryan** [comment]
On 0.5.2 with a config.ini file I'm getting ... note that Username has an extra n (might just be the message).  I have username specified in my ini file as shown.

Locast2Plex v0.5.2
Tuner count set to 3
UUID set to: xjnmkzoo...
Usernanme not specified in config.ini.  Exiting...
Exiting...

[main]
username=<email>
password=<pw>
plex_accessible_ip=<ip>
uuid=<python script adds>

**Comment by tri-ler** [comment]
Look at the config_example.ini file. It should be 

...
locast_username= XXX
locast_password= XXX
...

**Comment by jamesmalachyryan** [comment]
Thank you! That was the problem. 

I got my file format from https://hub.docker.com/r/tgorg/locast2plex middle of the page.

**Comment by zerolimit30** [comment]
Could someone help me. I am using urnaid i dont see were i can put the ini file. here are my settings on unraid docker 
https://i.imgur.com/7KbOQRC.png

thanks for the help!

**Comment by jamesmalachyryan** [comment]
I don/t use unraid.  I use docker on Linux.  In docker-compose I defined a docker volume as:

    volumes:
      - /docker/locast2plex/config.ini:/app/config.ini

My guess is you should be able to do something similar under "docker allocations" or more settings in your screen shot.

**Comment by jamesrseeman** [comment]
I am running unraid.

I resolved the issue by adding a 'PATH' to my docker with the following:

-   Config Type: Path
-   Name: config
-   Container Path:  /app
-   Host Path:  /mnt/cache/appdata/locast2plex
-   Access Mode: Read/Write


And I created my config.ini in /mnt/cache/appdata/locast2plex

Hope this helps.

**Comment by tgorgdotcom** [comment]
Sorry about all the trouble the change to using a config.ini caused.  There were quite a few different reasons for using this versus environment variables. 

@dcd, sounds good.  I can put in a few checks for different locations for config.ini, one being outside of `/app`.

**Comment by zerolimit30** [comment]
> I am running unraid.
> 
> I resolved the issue by adding a 'PATH' to my docker with the following:
> 
> * Config Type: Path
> * Name: config
> * Container Path:  /app
> * Host Path:  /mnt/cache/appdata/locast2plex
> * Access Mode: Read/Write
> 
> And I created my config.ini in /mnt/cache/appdata/locast2plex
> 
> Hope this helps.

i did this (thanks) but now i am getting this on unraid

------------------
python: can't open file '/app/main.py': [Errno 2] No such file or directory
------------------

**Comment by zerolimit30** [comment]
here are my unraid docker settings

https://i.imgur.com/ejkgAcl.png

**Comment by tgorgdotcom** [comment]
Hello @zerolimit30 .  You have to mount the file instead of the folder.  For instance: 
```
/mnt/cache/appdata/locast2plex/config.ini 
Container path: /app/config.ini
```

**Comment by zerolimit30** [comment]
> Hello @zerolimit30 . You have to mount the file instead of the folder. For instance:
> 
> ```
> /mnt/cache/appdata/locast2plex/config.ini 
> Container path: /app/config.ini
> ```

that fix the problem thank you.
