### ISSUE TITLE
Tuner count in Main.py

### ISSUE THREAD

**Issue by tharris9d** [tgorgdotcom/locast2plex#67]
The below code wouldn't let me set 4 tuners.
main.py line 305

 if (TUNER_COUNT **>=** 4) or (TUNER_COUNT < 1):
        print("Tuner count set outside of 1-4 range.  Setting to default")
        TUNER_COUNT = 3

**Should be**
 if **(TUNER_COUNT > 4)** or (TUNER_COUNT < 1):
        print("Tuner count set outside of 1-4 range.  Setting to default")
        TUNER_COUNT = 3

**Comment by ratherDashing** [comment]
https://github.com/tgorgdotcom/locast2plex/pull/73

yer right, easy fix

**Comment by tgorgdotcom** [comment]
Yikes, my bad.  Pull request is merged.
