### ISSUE TITLE
GeoLocation Error (Error 1)

### ISSUE THREAD

**Issue by DanTheTechMan** [tgorgdotcom/locast2plex#68]
Hi,

I was in the process of setting up L2P. I have downloaded and installed Python 2.7.1, created the directory for L2P, downloaded the files from GitHub, copied the files to the directory I created, and ran the "main.py" script from the command line (I cannot use Docker, as my system doesn't support it). For whatever reason, I can't get past the GeoLocation step. I get "Error 1" wit the following output:

Getting user location...
Error during geo IP acquisition: [Errno 1] _ssl.c:499: error:14077410:SSL routin
es:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
Exiting...

Is there something I'm doing wrong? If not, can this be fixed? Any help would be greatly appreciated.

Thanks.

**Comment by ratherDashing** [comment]
i believe python 2.7.9 fixed this?  update to the latest python 2.7.x and try again
