### ISSUE TITLE
ERROR:root:need more than 1 value to unpack

### ISSUE THREAD

**Issue by plutoniumshore** [tgorgdotcom/locast2plex#7]
I think I'm doing this correctly...Should I be worried about the repeating error line?

"ERROR:root:need more than 1 value to unpack"

Subsequently, plex sees the DVR, loads the guides without issue..but streams fail to start when I hit play. Ive tried this on two different machines to try and rule out the OS/environment being an issue.  I may have done something incorrectly.  Looking up the error does not give me any additional insight that makes sense.

Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 1593690022
Getting user location...
User location obtained as 42.2917/-71.7858
Getting user's media market (DMA)...
DMA found as 506
Getting list of stations based on DMA...
Loading FCC Stations list...
Starting device server on 0.0.0.0:6077
Starting SSDP server...
ERROR:root:need more than 1 value to unpack
ERROR:root:need more than 1 value to unpack
ERROR:root:need more than 1 value to unpack
ERROR:root:need more than 1 value to unpack
ERROR:root:need more than 1 value to unpack
ERROR:root:need more than 1 value to unpack
ERROR:root:need more than 1 value to unpack
10.0.0.101 - - [02/Jun/2020 09:45:14] "GET /device.xml HTTP/1.1" 200 -

**Comment by tgorgdotcom** [comment]
Just pushed an update (0.4.0).  I don't know if that fixed your issue, but if you could try updating and respond back, that would be great.  Thanks!

**Comment by plutoniumshore** [comment]
Still getting the same repeating error.  I also tried the docker and saw the same repeating error.  It could totally be me.  Is there anything obvious that I may be doing wrong?

C:\locast>python main.py -u:username@domain.com -p:password --debug --addy:10
.0.0.101
Locast2Plex v0.4.1
No UUID found.  Generating one now...
UUID set to: XXXXXXXX...
Logging into Locast using username username@domain.com...
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 1593690022
Getting user location...
User location obtained as 42.2917/-71.7858
Getting user's media market (DMA)...
DMA found as 506
Getting list of stations based on DMA...
Loading FCC Stations list...
Starting device server on 0.0.0.0:6077
Starting SSDP server...
ERROR:root:need more than 1 value to unpack
ERROR:root:need more than 1 value to unpack
ERROR:root:need more than 1 value to unpack
ERROR:root:need more than 1 value to unpack
ERROR:root:need more than 1 value to unpack

**Comment by tgorgdotcom** [comment]
Hmmm.  This is very strange.  A couple of things:

- What version of python are you using (`python ––version` command will yield what were looking for)
- Could you give me a step by step list of how you installed locast2plex (any method you choose is fine).

**Comment by plutoniumshore** [comment]
2.7.18 (Should I be using 3?)

1. Installed python with default settings
2. Put environment variable for python to execute from cmdline
3. extracted Locast folder to root of C: and renamed "C:\Locast"
4. Installed FFMpeg (just in case) and put environment variable to execute from cmdline
5. opened command prompt with admin privs and executed as per above.

Tried this on two different machines (same install) with win7 and win10
Also tried docker before 4.0/4.1 (for some reason I was getting an error pulling the new 4.0/4.1 docker images) and would still get the error.  I was running docker on Ubuntu server headless.

**Comment by plutoniumshore** [comment]
Well...I still haven't cleared the error..but I finally got it working through docker.  Thanks for the assist!
(Changed my guide settings and managed to get 5 channels working)

**Comment by jandreaucodes** [comment]
I'm seeing this same error when I run the script in Terminal.

macOS 10.15.6
Python 2.7.15
