### ISSUE TITLE
Change tuner type from Antenna to Cable

### ISSUE THREAD

**Issue by thowilli** [tgorgdotcom/locast2plex#70]
Is it possible to change the tuner type from Antenna to Cable?  So it would show up in Plex with a type Cable when adding the DVR in settings?

**Comment by tgorgdotcom** [comment]
Not sure whether this would affect how Plex does EPG.  Could you describe what you want to accomplish with this change?  Thanks!

**Comment by thowilli** [comment]
I tried to add locast2plex as an additional DVR to Plex but it wouldn’t let me select a guide since my other DVR is tuner type cable.  They only allow one type at a time.  I decided to just create an additional Plex server with only a DVR configured for locast2plex and it’s been working great so far.  Thanks for creating this!  It’s awesome!
