### ISSUE TITLE
Config or readme is not correct

### ISSUE THREAD

**Issue by mneumark** [tgorgdotcom/locast2plex#72]
I have been using this for a bit and suddenly it wouldn't start. Checked, and turns out I updated my docker container and it uses the config.ini file now. So I set that up as it says in the README. I kept getting "Usernanme not specified in config.ini. Exiting.." errors. Finally looked in your code and it turns out its not looking for `username` and `password` as specified in the README. It's looking for `locast_username` and `locast_password`. I changed the variable names in the config file to those, and everything works again. Just thought I should make you aware of it as not everyone is quite as willing to dig into code as I am 🙂

**Comment by tgorgdotcom** [comment]
Shoot, sorry about that!  Excellent catch!

**Comment by tgorgdotcom** [comment]
All fixed now in `latest`
