### ISSUE TITLE
ffmpeg ideas

### ISSUE THREAD

**Issue by deathbybandaid** [tgorgdotcom/locast2plex#74]
Stealing an idea from dizquetv, but there should be a way to utilize ffmpeg to do some cool stuff.

We should (in theory) allow Plex/Emby/Jellyfin to connect to locast2plex immediately, and display a loading image while the content pulls in with `bytes_per_read`.

We can then also display an error image if the stream breaks, and potentially reattempt the stream.

**Comment by jcastilloalonso** [comment]
This would be pretty neat! My experience with ffmpeg is pretty limited but it would be nice to have faster load times and error messages (and reattempts) integrated.

**Comment by deathbybandaid** [comment]
Gosh, I just can't seem to crack this! If anybody with more ffmpeg experience can take a look at this, I'd be grateful.

I'm fairly certain we need to make ffmpeg's input `stdin`. Doing so would allow us to change the input on-the-fly, and we'd be able to inject:

* Loading screen
* Error screen
* Debug error screen (overlay information on black image)
* Nerdstats mode (overlay information over live stream)


The jist of what I was trying to accomplish:


````
ffmpetg_command = [self.ffpmeg_path,
                               "-protocol_whitelist", 'file,http,https,tcp,tls',
                               "-i", "/dev/stdin",
                               "-c:v", "copy",
                               "-c:a", "copy",
                               "-f", "mpegts",
                               "-nostats", "-hide_banner",
                               "-loglevel", "warning",
                               "pipe:1"
                               ]

ffmpeg_proc = subprocess.Popen(ffmpetg_command,
                                           stdin=subprocess.PIPE,
                                           stdout=subprocess.PIPE,
                                           shell=False)

ffmpeg_proc.stdin.write(channelUri)

videoData = ffmpeg_proc.stdout.read(self.bytes_per_read)
````

**Comment by deathbybandaid** [comment]
OR, maybe this involves 2 seperate ffmpegs running

**Comment by FozzieBear** [comment]
Concat is probably the easiest way to chain\swap inputs with ffmpeg. 
https://trac.ffmpeg.org/wiki/Concatenate
