### ISSUE TITLE
Not an issue just a question - Also THANK YOU GUYS THIS WORKS GREAT

### ISSUE THREAD

**Issue by libersongm** [tgorgdotcom/locast2plex#77]
All,
Thank you so much for locast2plex!  It was easy to install and get going.  Was wondering, the tuner_count limit is 3.  Locast allows 4 streams.  Looking at the code would changing the default to 4 be an issue?   Not complaining at all, just asking.  PS installed super easy little to no issues as a user scripted started at login.   Thanks again and really appreciate the tool.

Thanks in advance.

Very Respectfully,
Gary

**Comment by jcastilloalonso** [comment]
This was integrated based on #9

The default was decided as 3, as 4 has potential issue of getting an error during fast channel switching. Where the stream is still not closed and the next one will fail to load.

**Comment by deathbybandaid** [comment]
The alternative would be forcing a 30 second wait time every channel switch.

**Comment by libersongm** [comment]
Thank you again for all the help.  

Very Respectfully,
Gary
