### ISSUE TITLE
Error when running main.py

### ISSUE THREAD

**Issue by slayernfc** [tgorgdotcom/locast2plex#8]
Locast2Plex v0.4.0
DEBUG MODE ACTIVE
UUID found.
UUID set to: mivyttyx...
Logging into Locast using username username@gmail.com... 
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 1594161231
Getting user location...
User location obtained as 28.1355/-82.4605
Getting user's media market (DMA)...
DMA found as 539
Getting list of stations based on DMA...
Loading FCC Stations list...
Traceback (most recent call last):
  File "main.py", line 324, in <module>
    station_list = locast.get_stations()
  File "/home/slayer/locast2plex-master/LocastService.py", line 195, in get_stations
    fcc_market = dma_mapping[str(self.current_dma)]
KeyError: '539'

**Comment by tgorgdotcom** [comment]
Hello there.  I pushed an update (0.4.1) to support the new market just released.  You'll need to re-pull the image and update your container to get it working.  Let me know if that fixes your issue.  Thanks!

**Comment by slayernfc** [comment]
it seems to be working good, thank you
