### ISSUE TITLE
Error during geo IP acquisition: [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by shayaknyc** [tgorgdotcom/locast2plex#83]
Hey folks,

Just updated to Locast2Plex v0.5.2, updated the config.ini with the params it needed. This is the output I now receive:

```
Locast2Plex v0.5.2
Tuner count set to 3
No UUID found.  Generating one now...
UUID set to: whwktwsl...
Logging into Locast using username [OBSCURED EMAIL ADDRESS]...
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 1602991625
Getting user location...
Error during geo IP acquisition: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)                                                                                         Exiting...
```

Not sure there's anything I can do about the SSL cert not being verifiable....any setting I can change in the code to have it skip SSL checks? I know there are dangers to this, but it seems as if the destination it's trying to connect to for geo IP lookups has an invalid cert and now this won't work at all.

Here's my config.ini:

```
[main]
locast_username = [OBSCURED EMAIL]
locast_password = [OBSCURED PASSWORD]
plex_accessible_ip = 10.0.0.2
uuid = whwktwsl
```

Any ideas?

**Comment by tgorgdotcom** [comment]
Hello.  What platform are you running this on?

**Comment by shayaknyc** [comment]
Python 2.7 in Ubuntu 18.04 under Windows 10 WSL. It was working fine before the upgrade, but now the error mysteriously disappeared and is working again.

**Comment by mikeh143** [comment]
Which version of Python? I had some SSL issues with Python 2.7.8, but upgrading to 2.7.9 fixed them for me. It was a different error, but might help you as well

**Comment by shayaknyc** [comment]
Actually, I'm on 2.7.17

--Shaya

**Comment by tgorgdotcom** [comment]
@shayaknyc , Just to confirm, is this working correctly for you now?

**Comment by shayaknyc** [comment]
@tgorgdotcom yes, confirmed, it's now working. I didn't change anything, so perhaps the SSL was verified? I was just wondering if there was a way to ignore SSL checks?

**Comment by tgorgdotcom** [comment]
There are a couple of ways.  We changed the geoIP mechanism in 0.5.3, so that might help.  If that doesn't work, there's a way to override location, bypassing the geoIP step entirely
