### ISSUE TITLE
Config error even though I have a config file

### ISSUE THREAD

**Issue by MervisDiamonds** [tgorgdotcom/locast2plex#86]
I'm sure this is a simple fix but I'm running into the following error on my qnap container station.

```
Locast2Plex v0.5.2
Tuner count set to 3
No UUID found. Generating one now...
config_handler.set('main', 'uuid', DEVICE_UUID)
File "/usr/lib/python2.7/ConfigParser.py", line 396, in set
raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'main' 
```

my install is below`docker create \
--name= tgorg/locast2plex \
-v /share/CACHEDEV1_DATA/Download/LocastData/config.ini/:/app/config/config.ini \
-p 6077:6077 \
-p 1900:1900/udp \
-e username=xxxxxx \
-e password=xxxxx \
-e external_addy=192.168.xx.xx \
-e external_port=6077 \
tgorg/locast2plex –debug
`

**Comment by kingstonwa** [comment]
I'm getting the same errors on my Qnap, seems that vers. .05 is a bit buggy? 
Similar problem here: https://forums.unraid.net/topic/95907-request-locast2plex-docker/

**Comment by MervisDiamonds** [comment]
I figured it out.  Basically,  everything is in the config.  It will run with this:

```
docker run  \
-v /share/CACHEDEV1_DATA/Download/LocastData/config.ini:/app/config/config.ini \
tgorg/locast2plex  --debug

```
Looks like I need to donate to test further.

**Comment by kingstonwa** [comment]
I just tried that and got an error for login although my credentials are correct in my config.ini

Locast2Plex v0.5.2                                                                                                                                           
Tuner count set to 3                                                                                                                                         
UUID set to: lmxjmviw...                                                                                                                                     
Logging into Locast using username [myname]@gmail.com...                                                                                                
Error in function login:                                                                                                                                     
Exiting...

**Comment by MervisDiamonds** [comment]
I've graduated to my next problem.  Now I can't get plex to add the locast2plex "tuner".  I've tried the loopback address and others without luck so far.

**Comment by MervisDiamonds** [comment]
Fixed!  I used "docker inspect" to find my IP address.  Once I entered it, it worked right away.

New problem, I can't see any content. LOL

**Comment by MervisDiamonds** [comment]
I entered the external IP in config to the docker assigned IP address, and now HDhomerun tuner and locast2plex are working as expected.

**Comment by kingstonwa** [comment]
@MervisDiamonds , where do I source the  "docker inspect" tool?

**Comment by MervisDiamonds** [comment]
You use it in terminal/command line.  docker inspect [name of locast2plex container]

**Comment by kingstonwa** [comment]
Finally got mine working using your config recommendation, thanks @MervisDiamonds
