### ISSUE TITLE
Immediately fails when playing live video

### ISSUE THREAD

**Issue by scumola** [tgorgdotcom/locast2plex#89]
Just pulled the latest from git and plex immediately fails when trying to play live video

Running in cli-mode (non-docker) on linux with python 2.7.

Also, I don't see a /watch/ url come through at all, but when I hit the play button on plex's guide, I get three hits immediately to /lineup, /discover and /lineup_status.

Tried with the linux plex client and the web client using firefox on linux

```
~/locast2plex$ python main.py 
Locast2Plex v0.5.2
Tuner count set to 3
UUID set to: (removed)...
Logging into Locast using username (removed)...
Validating User Info...
User Info obtained.
User didDonate: True
User donationExpire: 2020-11-05 19:30:19
Getting user location...
Getting location via IP Address.
Got external IP (removed).
Got location as Denver - (removed)
Getting list of stations based on DMA...
Loading FCC Stations list...
Starting device server on 0.0.0.0:6077
Starting SSDP server...
Locast2Plex is active and listening...
10.0.0.23 - - [15/Sep/2020 16:28:28] "GET /lineup.json HTTP/1.0" 200 -
10.0.0.23 - - [15/Sep/2020 16:28:28] "GET /discover.json HTTP/1.0" 200 -
10.0.0.23 - - [15/Sep/2020 16:28:28] "GET /lineup_status.json HTTP/1.0" 200 -
^C^C received, shutting down the server
```

When setting it up, it pulled the channels and lineup just fine.  It's just playing live video that seems to be broken.

**Comment by FozzieBear** [comment]
If you go to `serverip:6077/lineup.json` in a web browser, what's one of the values for `"URL": `?

**Comment by scumola** [comment]
Ahaa!  "URL": "http://0.0.0.0:6077/watch/752"

**Comment by scumola** [comment]
I guess I can't listen on 0.0.0.0 then.  Maybe changing to the IP will fix?

**Comment by scumola** [comment]
Ok, so that fixed that issue.  :+1:  Closing
