### ISSUE TITLE
Keep getting error - "Logging into Locast using username username..."

### ISSUE THREAD

**Issue by okayyeahsure** [tgorgdotcom/locast2plex#96]
I keep having an issue where I am getting the error "Logging into Locast using username username..." 

The config.ini has my username/email and password, so I can't figure out why it is coming back with "username username"

I am running this through Terminal on a Mac. This is the full output I am getting:

> docker run -v config.ini -p 6077:6077 -p 1900:1900/udp tgorg/locast2plex
> 
> Locast2Plex v0.4.2
> DEBUG MODE ACTIVE
> UUID found.
> UUID set to: lrtrvhsi...
> Logging into Locast using username username...
> Error during login: Not Found
> Exiting...

Any ideas? Thanks

**Comment by deathbybandaid** [comment]
I'm not a docker user, so I could be wrong,,,

-v <full path to config file>:/app/config/config.ini

Don't you have to do full path th config file, as well as the stuff after the colon? That way it maps the file on host machine to a place in the container?

**Comment by okayyeahsure** [comment]
I have been trying all sorts of combinations including the full file path from the base folder in Terminal. The ones I posted in my original question was when I was trying to execute it directly from the folder Locast2Plex was in. Neither have worked for me.

**Comment by tgorgdotcom** [comment]
Hello @okayyeahsure.  You're using version 0.4.2.  `config.ini` doesn't work until 0.5.x.  You'll need to pull the latest image from docker.

**Comment by okayyeahsure** [comment]
Sorry, I'm fairly new to Docker. How would I pull the latest image? The version I have is the most recent one on github. Sorry if this is too much to get into. If it is I can move on, but I am just really interested in getting this working. Thanks

**Comment by tgorgdotcom** [comment]
Try `docker pull tgorg/locast2plex`.  

Then run the command like so: 
`docker run -v <Full path to config.ini>:/app/config/config.ini -p 6077:6077 -p 1900:1900/udp tgorg/locast2plex`

**Comment by okayyeahsure** [comment]
That worked! Thank you!

**Comment by tgorgdotcom** [comment]
Awesome, no problem.
