### ISSUE TITLE
m3u8 import

### ISSUE THREAD

**Issue by deathbybandaid** [tgorgdotcom/locast2plex#97]
I just did a test. `pip3 install m3u8`, and I removed the copy from the local directory.

Works just great. Topic for discussion: adding a `requirements.txt` to the repo, and not maintaining a version of this in our repo.

For CLI users, it's a simple `pip3 install -r requirements.txt`

For docker, a similar `RUN pip3 install -r requirements.txt`

**Comment by deathbybandaid** [comment]
I've also read that ffmpeg/m3u8 should automatically select the best quality, so manually doing so in this script may be pointless.

**Comment by tgorgdotcom** [comment]
Hmmm.  This is better in a lot of ways, but it does create a breaking change for those who wish to upgrade.  What do you think about making this a major revision change?  Right now we're in beta, but for now I generally want to get into the habit of not making large breaking changes at this point (from a user perspective -- I think most of the other behind the scenes/new features changes are okay).  But once we hit 1.0, we can start to make breaking changes for 2.x.

**Comment by deathbybandaid** [comment]
Actually, with the project in beta, the best time for breaking changes is before 1.0 .

**Comment by deathbybandaid** [comment]
Alot of the stuff proposed in #92 is breaking changes. I'd say we merge that and label it as a release candidate.

**Comment by tgorgdotcom** [comment]
To be clear, I'm chiefly worried about changes in configuration, or if something changed in how a user would set up locast2plex. 
 I'm fine with code re-organization changes or if we introduce bugs (or even new features that don't change the the setup process).   I do have a few thoughts on #92, which I'll send a post about shortly, but it's mostly good in my eyes.

Indeed, for the most part you would be right about beta.  But, we've had considerable growth and new users over the last few months.  It went from being just a small script to something bigger, and I didn't really have a plan for breaking changes, etc. at the beginning.  We have over 100k pulls from docker hub, and quite a few people struggling through getting everything setup.  It also seems that some users upgrade from point releases expecting no setup changes (0.4.x -> 0.5.x for instance).  

My main thought now is to start using '-alpha' and '-beta' postfixes to releases, but only after 1.0.  That way users understand more clearly what they're getting into when updating.

Hopefully that cleared some things up.
