### ISSUE TITLE
Upgraded to 0.5.3 from 0.5.0 and black screen while viewing.  OK Audio.

### ISSUE THREAD

**Issue by gbcue** [tgorgdotcom/locast2plex#99]
I just upgraded the docker to 0.5.3 from 0.5.0 (in unraid) and now when I try to view live TV, all I get is a black screen.  The audio comes through just fine.

Everything was working fine in 0.5.0, including recording features in Plex.  I have tried this on a desktop using the latest Firefox browser and Plex apps on my tablet and phone.  All show blank screen but audio.  I have also tried removing the tuner in Plex and re-adding it.  Same problem.

Plex version:  1.20.1.3252

**Comment by FozzieBear** [comment]
To check if this is a Plex or Locast issue, go to http://x.x.x.x/lineup.json, (where x.x.x.x is the IP that locast2plex is running on) and plug one of the URLs into VLC (Media > Open Network Stream...) or another player. Do you get video and sound there? Does rolling the container back to 0.5.0 resolve the issue?

**Comment by gbcue** [comment]
Ok, it seemed like it was a Locast issue where some stations were just not loading a few days ago.  It looks like all stations are working now.
